### ISSUE TITLE
Timezone Error = 'None'

### ISSUE THREAD

**Issue by unamuno** [fossasia/open-event-server#4460]
**I'm submitting a ...**  (check one with "x")
- [ x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
HTTP 500

**Expected behavior:**
Event Detail Page is loading

**Steps to reproduce:**
Activate the Ticket Plugin and save the public event

**Related code:**

```
Exception on /e/9c4251f3/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/api.py", line 557, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/merlin/open-event-orga-server/app/views/public/event_detail.py", line 103, in display_event_detail_home
    code=code)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/merlin/open-event-orga-server/app/templates/gentelella/guest/event/details.html", line 65, in top-level template code
    <img alt="{{ sponsor.name }}" src="{{ sponsor.logo }}">
  File "/home/merlin/open-event-orga-server/app/templates/gentelella/guest/event/base.html", line 21, in top-level template code
    {% set event_image = url_for("static", filename="placeholders/" + placeholder_images["Other"], _external=True) %}
  File "/home/merlin/open-event-orga-server/app/templates/gentelella/base.html", line 58, in top-level template code
    {% block body %}
  File "/home/merlin/open-event-orga-server/app/templates/gentelella/guest/event/base.html", line 182, in block "body"
    {% block content %}
  File "/home/merlin/open-event-orga-server/app/templates/gentelella/guest/event/details.html", line 80, in block "content"
    {% include 'gentelella/guest/event/_ticketing_box.html' %}
  File "/home/merlin/open-event-orga-server/app/templates/gentelella/guest/event/_ticketing_box.html", line 56, in top-level template code
    <td>{{ ((ticket.ticket.sales_end|localize_dt_obj(event.timezone))|as_timezone(current_timezone)).strftime('%a, %B %d') }}</td>
  File "/home/merlin/open-event-orga-server/app/helpers/flask_ext/jinja/filters.py", line 123, in as_timezone
    if timezone(tzname):
  File "/usr/local/lib/python2.7/dist-packages/pytz/__init__.py", line 181, in timezone
    raise UnknownTimeZoneError(zone)
UnknownTimeZoneError: 'None'
```

**Other information:**

**System information:** 

```
Ubuntu 16.04 LTS
```

```
Python 2.7.12
```

**Comment by lucasruchel** [comment]
Hello @unamuno, 

I'm new in python and with Github. I had the same problem and I solved changing the file `app/helpers/wizard/helpers.py`

```
from tzlocal import get_localzone

def get_current_timezone():
    match = str(get_localzone())
    if match is not None:
        return match
    else:
        return 'UTC'
```
If anyone can validate :)

**Comment by unamuno** [comment]
Sorry, I made the change and restarted but the bug is still there.

**Comment by unamuno** [comment]
Maybe it is not allowed to place a Webproxy in front of the Webapp? I'm using nginx.

**Comment by lucasruchel** [comment]
Try to verify in your database if timezone was setted in events table.

**Comment by unamuno** [comment]
@lucasruchel It is set correctly: 

```
oevent2=# SELECT timezone, name FROM events;
   timezone    |            name             
---------------+-----------------------------
 Europe/Berlin | Juki-Academy: Workshop Days
(1 row)
```

**Comment by mohitkyadav** [comment]
@unamuno can you mention the url, you are facing the error. cause I didn't get any error on `http://localhost:8001/v1/events/1`

**Comment by unamuno** [comment]
I'm sorry, but I stoped using this project and the installation is not running anymore. :/

**Comment by niranjan94** [comment]
@open-event-bot move to fossasia/open-event-legacy
