### ISSUE TITLE
Event Export is not working

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#4609]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**

**Heroku Error logs**:

```
[2018-01-28 20:35:31,453: ERROR/MainProcess] Task export.event[11cf63e0-729c-4caf-b3d8-7afb40329f14] raised unexpected: OperationalError('(psycopg2.OperationalError) server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n',)
2018-01-28T20:35:31.464634+00:00 app[web.1]: Traceback (most recent call last):
2018-01-28T20:35:31.464636+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
2018-01-28T20:35:31.464641+00:00 app[web.1]: R = retval = fun(args, **kwargs)
2018-01-28T20:35:31.464643+00:00 app[web.1]: File "/app/app/api/helpers/request_context_task.py", line 46, in call
2018-01-28T20:35:31.464645+00:00 app[web.1]: result = call()
2018-01-28T20:35:31.464647+00:00 app[web.1]: File "/app/app/api/helpers/request_context_task.py", line 32, in <lambda>
2018-01-28T20:35:31.464648+00:00 app[web.1]: call = lambda: super(RequestContextTask, self).call(args, kwargs)
2018-01-28T20:35:31.464650+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/celery/app/trace.py", line 438, in protected_call
2018-01-28T20:35:31.464651+00:00 app[web.1]: return self.run(*args, kwargs)
2018-01-28T20:35:31.464652+00:00 app[web.1]: File "/app/app/api/helpers/tasks.py", line 60, in export_event_task
2018-01-28T20:35:31.464653+00:00 app[web.1]: event = safe_query(db, Event, 'id', event_id, 'event_id')
2018-01-28T20:35:31.464655+00:00 app[web.1]: File "/app/app/api/helpers/db.py", line 45, in safe_query
2018-01-28T20:35:31.464656+00:00 app[web.1]: record = self.session.query(model).filter(getattr(model, column_name) == value).one()
2018-01-28T20:35:31.464658+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2814, in one
2018-01-28T20:35:31.464661+00:00 app[web.1]: ret = self.one_or_none()
2018-01-28T20:35:31.464662+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2784, in one_or_none
2018-01-28T20:35:31.464663+00:00 app[web.1]: ret = list(self)
2018-01-28T20:35:31.464664+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2855, in iter
2018-01-28T20:35:31.464666+00:00 app[web.1]: return self._execute_and_instances(context)
2018-01-28T20:35:31.464667+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
2018-01-28T20:35:31.464668+00:00 app[web.1]: result = conn.execute(querycontext.statement, self._params)
2018-01-28T20:35:31.464670+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
2018-01-28T20:35:31.464671+00:00 app[web.1]: return meth(self, multiparams, params)
2018-01-28T20:35:31.464672+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
2018-01-28T20:35:31.464674+00:00 app[web.1]: return connection._execute_clauseelement(self, multiparams, params)
2018-01-28T20:35:31.464675+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
2018-01-28T20:35:31.464676+00:00 app[web.1]: compiled_sql, distilled_params
2018-01-28T20:35:31.464677+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
2018-01-28T20:35:31.464679+00:00 app[web.1]: context)
2018-01-28T20:35:31.464680+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
2018-01-28T20:35:31.464681+00:00 app[web.1]: exc_info
2018-01-28T20:35:31.464683+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
2018-01-28T20:35:31.46
_
 
```

**Comment by mayank8318** [comment]
@srv-twry Yes, event export works now
