### ISSUE TITLE
Event import end point not working

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#4613]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**

Event import end point gives the following error
```python
2018-01-31T14:49:27.762635+00:00 app[web.1]: get_file_from_request() INVOKED. We have: request.files = ImmutableMultiDict([])
2018-01-31T14:49:27.765722+00:00 app[web.1]: [2018-01-31 14:49:27 +0000] [54] [ERROR] Exception in worker process
2018-01-31T14:49:27.765724+00:00 app[web.1]: Traceback (most recent call last):
2018-01-31T14:49:27.765726+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
2018-01-31T14:49:27.765727+00:00 app[web.1]:     worker.init_process()
2018-01-31T14:49:27.765728+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 131, in init_process
2018-01-31T14:49:27.765730+00:00 app[web.1]:     self.run()
2018-01-31T14:49:27.765731+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 124, in run
2018-01-31T14:49:27.765732+00:00 app[web.1]:     self.run_for_one(timeout)
2018-01-31T14:49:27.765734+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 68, in run_for_one
2018-01-31T14:49:27.765735+00:00 app[web.1]:     self.accept(listener)
2018-01-31T14:49:27.765736+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 30, in accept
2018-01-31T14:49:27.765737+00:00 app[web.1]:     self.handle(listener, client, addr)
2018-01-31T14:49:27.765739+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
2018-01-31T14:49:27.765740+00:00 app[web.1]:     self.handle_request(listener, req, client, addr)
2018-01-31T14:49:27.765741+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
2018-01-31T14:49:27.765742+00:00 app[web.1]:     respiter = self.wsgi(environ, resp.start_response)
2018-01-31T14:49:27.765743+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
2018-01-31T14:49:27.765745+00:00 app[web.1]:     return self.wsgi_app(environ, start_response)
2018-01-31T14:49:27.765746+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/raven/middleware.py", line 100, in __call__
2018-01-31T14:49:27.765747+00:00 app[web.1]:     iterable = self.application(environ, start_response)
2018-01-31T14:49:27.765748+00:00 app[web.1]:   File "/app/app/__init__.py", line 71, in __call__
2018-01-31T14:49:27.765749+00:00 app[web.1]:     return self.app(environ, start_response)
2018-01-31T14:49:27.765750+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
2018-01-31T14:49:27.765751+00:00 app[web.1]:     response = self.full_dispatch_request()
2018-01-31T14:49:27.765753+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
2018-01-31T14:49:27.765754+00:00 app[web.1]:     rv = self.dispatch_request()
2018-01-31T14:49:27.765755+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
2018-01-31T14:49:27.765756+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2018-01-31T14:49:27.765757+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask_jwt/__init__.py", line 177, in decorator
2018-01-31T14:49:27.765758+00:00 app[web.1]:     return fn(*args, **kwargs)
2018-01-31T14:49:27.765760+00:00 app[web.1]:   File "/app/app/api/imports.py", line 15, in import_event
2018-01-31T14:49:27.765761+00:00 app[web.1]:     file_path = get_file_from_request(['zip'])
2018-01-31T14:49:27.765762+00:00 app[web.1]:   File "/app/app/api/helpers/import_helpers.py", line 90, in get_file_from_request
2018-01-31T14:49:27.765763+00:00 app[web.1]:     raise NotFoundError(source='{}', detail='File not found')
2018-01-31T14:49:27.765764+00:00 app[web.1]: NotFoundError: <app.api.helpers.errors.NotFoundError instance at 0x7f93a1d78638>
```

**Comment by sainiak009** [comment]
I would like to work on this issue but I am gonna need some help from a mentor.

**Comment by sainiak009** [comment]
To reproduce the error I tried to create an event using API and I am getting an IOError: Corrupt/Invalid Image error on using create event api for original-image-url with sample request json and even I tried some others image URLs too

**Comment by bhaveshAn** [comment]
@mayank8318 Can this issue be closed or still something left.
