### ISSUE TITLE
Kubernetes Deployment Elasticsearch pods crashloopback 

### ISSUE THREAD

**Issue by pandeybk** [fossasia/open-event-server#4632]
**Current behavior:**
kubectl get pods -n elasticsearch
NAME                            READY     STATUS             RESTARTS   AGE
elasticsearch-d494f99d5-2v7nt   0/1       CrashLoopBackOff   21         1h

**Expected behavior:**
ES should be up and running

**Steps to reproduce:**
* Deploy open-event-server using kubernetes manifest file
* Check logs `kubectl logs elasticsearch-d494f99d5-2v7nt -n elasticsearch`

** ES Pods description: **
 ```
kubectl describe pods elasticsearch-d494f99d5-2v7nt -n elasticsearch
Name:           elasticsearch-d494f99d5-2v7nt
Namespace:      elasticsearch
Node:           ip-10-2-107-141.us-west-2.compute.internal/10.2.107.141
Start Time:     Sat, 17 Feb 2018 20:35:24 -0700
Labels:         component=elasticsearch
                pod-template-hash=805095581
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"elasticsearch","name":"elasticsearch-d494f99d5","uid":"056b5572-1453-11e8-93cf-02...
Status:         Running
IP:             100.121.210.59
Created By:     ReplicaSet/elasticsearch-d494f99d5
Controlled By:  ReplicaSet/elasticsearch-d494f99d5
Init Containers:
  init-sysctl:
    Container ID:  docker://aa1e4065691e7b0d16acfa4b1d80bd49497085a4154555240b63f2fbacbb2926
    Image:         busybox
    Image ID:      docker-pullable://busybox@sha256:1669a6aa7350e1cdd28f972ddad5aceba2912f589f19a090ac75b7083da748db
    Port:          <none>
    Command:
      sysctl
      -w
      vm.max_map_count=262144
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sat, 17 Feb 2018 20:35:37 -0700
      Finished:     Sat, 17 Feb 2018 20:35:37 -0700
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from elasticsearch-token-hdc7c (ro)
Containers:
  es:
    Container ID:   docker://bd1b0c029e183c5a3ba41ef3c1a8f94661d150006891d415c1aa98d7b4d43c73
    Image:          quay.io/pires/docker-elasticsearch-kubernetes:5.5.1
    Image ID:       docker-pullable://quay.io/pires/docker-elasticsearch-kubernetes@sha256:539441c17ef4c585a27bfbb2e37c6bdb9085ec586c67b1193cc607bfb3ef293c
    Ports:          9200/TCP, 9300/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sat, 17 Feb 2018 22:08:26 -0700
      Finished:     Sat, 17 Feb 2018 22:08:36 -0700
    Ready:          False
    Restart Count:  22
    Environment Variables from:
      elasticsearch  ConfigMap  Optional: false
    Environment:
      NAMESPACE:  elasticsearch (v1:metadata.namespace)
    Mounts:
      /data from es-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from elasticsearch-token-hdc7c (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  es-data:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  elasticsearch-token-hdc7c:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  elasticsearch-token-hdc7c
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.alpha.kubernetes.io/notReady:NoExecute for 300s
                 node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason      Age                From                                                 Message
  ----     ------      ----               ----                                                 -------
  Normal   Pulling     51m (x14 over 1h)  kubelet, ip-10-2-107-141.us-west-2.compute.internal  pulling image "quay.io/pires/docker-elasticsearch-kubernetes:5.5.1"
  Warning  FailedSync  1m (x408 over 1h)  kubelet, ip-10-2-107-141.us-west-2.compute.internal  Error syncing pod
```

***Logs:***
```
[2018-02-18T05:03:08,207][INFO ][o.e.n.Node               ] [1b08d1ee-6b9d-4a7c-8b38-094df711585c] initializing ...
[2018-02-18T05:03:08,343][INFO ][o.e.e.NodeEnvironment    ] [1b08d1ee-6b9d-4a7c-8b38-094df711585c] using [1] data paths, mounts [[/data (/dev/xvda1)]], net usable_space [91.1gb], net total_space [99.9gb], spins? [possibly], types [xfs]
[2018-02-18T05:03:08,343][INFO ][o.e.e.NodeEnvironment    ] [1b08d1ee-6b9d-4a7c-8b38-094df711585c] heap size [247.5mb], compressed ordinary object pointers [true]
[2018-02-18T05:03:08,345][INFO ][o.e.n.Node               ] [1b08d1ee-6b9d-4a7c-8b38-094df711585c] node name [1b08d1ee-6b9d-4a7c-8b38-094df711585c], node ID [fxnqWPgcTsOy_EX3b2xysg]
[2018-02-18T05:03:08,345][INFO ][o.e.n.Node               ] [1b08d1ee-6b9d-4a7c-8b38-094df711585c] version[5.5.1], pid[9], build[19c13d0/2017-07-18T20:44:24.823Z], OS[Linux/3.10.0-693.11.6.el7.x86_64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_131/25.131-b11]
[2018-02-18T05:03:08,348][INFO ][o.e.n.Node               ] [1b08d1ee-6b9d-4a7c-8b38-094df711585c] JVM arguments [-XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+DisableExplicitGC, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Xms256m, -Xmx256m, -Des.path.home=/elasticsearch]
[2018-02-18T05:03:10,356][INFO ][o.e.p.PluginsService     ] [1b08d1ee-6b9d-4a7c-8b38-094df711585c] loaded module [aggs-matrix-stats]
[2018-02-18T05:03:10,356][INFO ][o.e.p.PluginsService     ] [1b08d1ee-6b9d-4a7c-8b38-094df711585c] loaded module [ingest-common]
[2018-02-18T05:03:10,357][INFO ][o.e.p.PluginsService     ] [1b08d1ee-6b9d-4a7c-8b38-094df711585c] loaded module [lang-expression]
[2018-02-18T05:03:10,357][INFO ][o.e.p.PluginsService     ] [1b08d1ee-6b9d-4a7c-8b38-094df711585c] loaded module [lang-groovy]
[2018-02-18T05:03:10,357][INFO ][o.e.p.PluginsService     ] [1b08d1ee-6b9d-4a7c-8b38-094df711585c] loaded module [lang-mustache]
[2018-02-18T05:03:10,357][INFO ][o.e.p.PluginsService     ] [1b08d1ee-6b9d-4a7c-8b38-094df711585c] loaded module [lang-painless]
[2018-02-18T05:03:10,357][INFO ][o.e.p.PluginsService     ] [1b08d1ee-6b9d-4a7c-8b38-094df711585c] loaded module [parent-join]
[2018-02-18T05:03:10,357][INFO ][o.e.p.PluginsService     ] [1b08d1ee-6b9d-4a7c-8b38-094df711585c] loaded module [percolator]
[2018-02-18T05:03:10,357][INFO ][o.e.p.PluginsService     ] [1b08d1ee-6b9d-4a7c-8b38-094df711585c] loaded module [reindex]
[2018-02-18T05:03:10,357][INFO ][o.e.p.PluginsService     ] [1b08d1ee-6b9d-4a7c-8b38-094df711585c] loaded module [transport-netty3]
[2018-02-18T05:03:10,357][INFO ][o.e.p.PluginsService     ] [1b08d1ee-6b9d-4a7c-8b38-094df711585c] loaded module [transport-netty4]
[2018-02-18T05:03:10,358][INFO ][o.e.p.PluginsService     ] [1b08d1ee-6b9d-4a7c-8b38-094df711585c] no plugins loaded
[2018-02-18T05:03:13,511][INFO ][o.e.d.DiscoveryModule    ] [1b08d1ee-6b9d-4a7c-8b38-094df711585c] using discovery type [zen]
[2018-02-18T05:03:14,533][INFO ][o.e.n.Node               ] [1b08d1ee-6b9d-4a7c-8b38-094df711585c] initialized
[2018-02-18T05:03:14,533][INFO ][o.e.n.Node               ] [1b08d1ee-6b9d-4a7c-8b38-094df711585c] starting ...
[2018-02-18T05:03:14,735][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [1b08d1ee-6b9d-4a7c-8b38-094df711585c] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: No up-and-running site-local (private) addresses found, got [name:lo (lo), name:eth0 (eth0)]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.5.1.jar:5.5.1]
Caused by: java.lang.IllegalArgumentException: No up-and-running site-local (private) addresses found, got [name:lo (lo), name:eth0 (eth0)]
	at org.elasticsearch.common.network.NetworkUtils.getSiteLocalAddresses(NetworkUtils.java:187) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.common.network.NetworkService.resolveInternal(NetworkService.java:246) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.common.network.NetworkService.resolveInetAddresses(NetworkService.java:220) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.common.network.NetworkService.resolveBindHostAddresses(NetworkService.java:130) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.transport.TcpTransport.bindServer(TcpTransport.java:742) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.transport.netty4.Netty4Transport.doStart(Netty4Transport.java:173) ~[?:?]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:69) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.transport.TransportService.doStart(TransportService.java:209) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:69) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.node.Node.start(Node.java:692) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:277) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.5.1.jar:5.5.1]
	... 6 more
[2018-02-18T05:03:15,613][INFO ][o.e.n.Node               ] [1b08d1ee-6b9d-4a7c-8b38-094df711585c] stopping ...
[2018-02-18T05:03:15,618][INFO ][o.e.n.Node               ] [1b08d1ee-6b9d-4a7c-8b38-094df711585c] stopped
[2018-02-18T05:03:15,618][INFO ][o.e.n.Node               ] [1b08d1ee-6b9d-4a7c-8b38-094df711585c] closing ...
[2018-02-18T05:03:15,634][INFO ][o.e.n.Node               ] [1b08d1ee-6b9d-4a7c-8b38-094df711585c] closed
```

**Comment by pandeybk** [comment]
I think I figure out the problem here. I added in `NETWORK_HOST: "_local_"` in configmap and it started working. Here is my complete working sample,

```
apiVersion: v1
data:
  CLUSTER_NAME: "open-event-primary"
  DISCOVERY_SERVICE: "elasticsearch"
  NODE_MASTER: "true"
  NODE_DATA: "true"
  HTTP_ENABLE: "true"
  ES_JAVA_OPTS: "-Xms256m -Xmx256m"
  NETWORK_HOST: "_local_"
kind: ConfigMap
metadata:
  namespace: elasticsearch
  name: elasticsearch
```

**Comment by chetanyachopra** [comment]
is this solved ??
