### ISSUE TITLE
Unknown error 500 on creating Order

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#4658]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
Unknown error 500 on creating Order
```
{
  "data": {
    "attributes": {
      "payment-mode": "paypal",
      "country": "India",
      "status": "pending",
      "amount": "10"
    },
    "type": "order",
    "relationships": {
      "attendees": {
        "data": [
          {
            "id": "21",
            "type": "attendee"
          }
        ]
      },
      "event": {
        "data": {
          "id": "155",
          "type": "event"
        }
      }
    }
  }
}
```

**Expected behavior:**
Order should be created

**Steps to reproduce:**
Create order

**Comment by mayank8318** [comment]
@iamareebjamal @SaptakS Can I work on this issue?

**Comment by iamareebjamal** [comment]
Please go ahead

**Comment by mayank8318** [comment]
@iamareebjamal @SaptakS I am having difficulty reproducing the issue. I did the following things :
1) Created an event
2) Added tickets to the event
Then tried to add attendees to the event using the above-created ticket id but I get 405 error. Is there some detail or step that I am missing?

**Comment by iamareebjamal** [comment]
Please show the log

**Comment by mayank8318** [comment]
INFO:werkzeug:127.0.0.1 - - [17/Apr/2018 10:55:18] "POST /v1/attendees/1 HTTP/1.1" 405 -
127.0.0.1 - - [17/Apr/2018 10:55:41] "POST /v1/attendees/2 HTTP/1.1" 405 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2018 10:55:41] "POST /v1/attendees/2 HTTP/1.1" 405 -
127.0.0.1 - - [17/Apr/2018 11:02:19] "POST /v1/attendees/2 HTTP/1.1" 405 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2018 11:02:19] "POST /v1/attendees/2 HTTP/1.1" 405 -
127.0.0.1 - - [17/Apr/2018 11:02:26] "POST /v1/attendees/1 HTTP/1.1" 405 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2018 11:02:26] "POST /v1/attendees/1 HTTP/1.1" 405 -
127.0.0.1 - - [17/Apr/2018 11:04:22] "POST /v1/attendees/1 HTTP/1.1" 405 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2018 11:04:22] "POST /v1/attendees/1 HTTP/1.1" 405 -
127.0.0.1 - - [17/Apr/2018 11:05:52] "POST /v1/attendees/1 HTTP/1.1" 405 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2018 11:05:52] "POST /v1/attendees/1 HTTP/1.1" 405 -
127.0.0.1 - - [17/Apr/2018 11:09:09] "POST /v1/attendees/1 HTTP/1.1" 405 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2018 11:09:09] "POST /v1/attendees/1 HTTP/1.1" 405 -
can't compare offset-naive and offset-aware datetimes
Traceback (most recent call last):
  File "/home/mayank/OpenSource/open-event-server/app/api/helpers/db.py", line 23, in save_to_db
    db.session.commit()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 921, in commit
    self.transaction.commit()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2192, in flush
    self._flush(objects)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2312, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2276, in _flush
    flush_context.execute()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
    mapper, table, update)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 659, in _emit_update_statements
    lambda rec: (
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 485, in _collect_update_commands
    value, state.committed_state[propkey]) is not True:
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/sql/type_api.py", line 359, in compare_values
    return x == y
TypeError: can't compare offset-naive and offset-aware datetimes
ERROR:root:DB Exception! can't compare offset-naive and offset-aware datetimes
127.0.0.1 - - [17/Apr/2018 11:11:46] "POST /v1/tickets HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2018 11:11:46] "POST /v1/tickets HTTP/1.1" 500 -
can't compare offset-naive and offset-aware datetimes
Traceback (most recent call last):
  File "/home/mayank/OpenSource/open-event-server/app/api/helpers/db.py", line 23, in save_to_db
    db.session.commit()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 921, in commit
    self.transaction.commit()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2192, in flush
    self._flush(objects)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2312, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2276, in _flush
    flush_context.execute()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
    mapper, table, update)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 659, in _emit_update_statements
    lambda rec: (
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 485, in _collect_update_commands
    value, state.committed_state[propkey]) is not True:
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/sql/type_api.py", line 359, in compare_values
    return x == y
TypeError: can't compare offset-naive and offset-aware datetimes
ERROR:root:DB Exception! can't compare offset-naive and offset-aware datetimes
127.0.0.1 - - [17/Apr/2018 11:12:06] "POST /v1/tickets HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2018 11:12:06] "POST /v1/tickets HTTP/1.1" 500 -
can't compare offset-naive and offset-aware datetimes
Traceback (most recent call last):
  File "/home/mayank/OpenSource/open-event-server/app/api/helpers/db.py", line 23, in save_to_db
    db.session.commit()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 921, in commit
    self.transaction.commit()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2192, in flush
    self._flush(objects)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2312, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2276, in _flush
    flush_context.execute()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
    mapper, table, update)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 659, in _emit_update_statements
    lambda rec: (
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 485, in _collect_update_commands
    value, state.committed_state[propkey]) is not True:
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/sql/type_api.py", line 359, in compare_values
    return x == y
TypeError: can't compare offset-naive and offset-aware datetimes
ERROR:root:DB Exception! can't compare offset-naive and offset-aware datetimes
127.0.0.1 - - [17/Apr/2018 11:12:15] "POST /v1/tickets HTTP/1.1" 201 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2018 11:12:15] "POST /v1/tickets HTTP/1.1" 201 -
can't compare offset-naive and offset-aware datetimes
Traceback (most recent call last):
  File "/home/mayank/OpenSource/open-event-server/app/api/helpers/db.py", line 23, in save_to_db
    db.session.commit()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 921, in commit
    self.transaction.commit()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2192, in flush
    self._flush(objects)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2312, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2276, in _flush
    flush_context.execute()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
    mapper, table, update)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 659, in _emit_update_statements
    lambda rec: (
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 485, in _collect_update_commands
    value, state.committed_state[propkey]) is not True:
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/sql/type_api.py", line 359, in compare_values
    return x == y
TypeError: can't compare offset-naive and offset-aware datetimes
ERROR:root:DB Exception! can't compare offset-naive and offset-aware datetimes
127.0.0.1 - - [17/Apr/2018 11:12:22] "POST /v1/tickets HTTP/1.1" 201 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2018 11:12:22] "POST /v1/tickets HTTP/1.1" 201 -
127.0.0.1 - - [17/Apr/2018 11:12:28] "POST /v1/attendees/1 HTTP/1.1" 405 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2018 11:12:28] "POST /v1/attendees/1 HTTP/1.1" 405 -
can't compare offset-naive and offset-aware datetimes
Traceback (most recent call last):
  File "/home/mayank/OpenSource/open-event-server/app/api/helpers/db.py", line 23, in save_to_db
    db.session.commit()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 921, in commit
    self.transaction.commit()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2192, in flush
    self._flush(objects)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2312, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2276, in _flush
    flush_context.execute()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
    mapper, table, update)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 659, in _emit_update_statements
    lambda rec: (
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 485, in _collect_update_commands
    value, state.committed_state[propkey]) is not True:
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/sql/type_api.py", line 359, in compare_values
    return x == y
TypeError: can't compare offset-naive and offset-aware datetimes
ERROR:root:DB Exception! can't compare offset-naive and offset-aware datetimes
127.0.0.1 - - [17/Apr/2018 11:13:04] "POST /v1/tickets HTTP/1.1" 201 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2018 11:13:04] "POST /v1/tickets HTTP/1.1" 201 -
127.0.0.1 - - [17/Apr/2018 11:13:17] "POST /v1/attendees/1 HTTP/1.1" 405 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2018 11:13:17] "POST /v1/attendees/1 HTTP/1.1" 405 -
127.0.0.1 - - [17/Apr/2018 11:13:32] "POST /v1/attendees/1 HTTP/1.1" 405 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2018 11:13:32] "POST /v1/attendees/1 HTTP/1.1" 405 -
127.0.0.1 - - [17/Apr/2018 11:13:47] "POST /v1/attendees/2 HTTP/1.1" 405 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2018 11:13:47] "POST /v1/attendees/2 HTTP/1.1" 405 -
127.0.0.1 - - [17/Apr/2018 11:17:43] "GET /v1/events/1/tickets HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2018 11:17:43] "GET /v1/events/1/tickets HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2018 11:20:07] "GET /v1/events/2/tickets HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2018 11:20:07] "GET /v1/events/2/tickets HTTP/1.1" 200 -
can't compare offset-naive and offset-aware datetimes
Traceback (most recent call last):
  File "/home/mayank/OpenSource/open-event-server/app/api/helpers/db.py", line 23, in save_to_db
    db.session.commit()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 921, in commit
    self.transaction.commit()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2192, in flush
    self._flush(objects)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2312, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2276, in _flush
    flush_context.execute()
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
    mapper, table, update)
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 659, in _emit_update_statements
    lambda rec: (
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 485, in _collect_update_commands
    value, state.committed_state[propkey]) is not True:
  File "/home/mayank/anaconda2/envs/openevent/lib/python2.7/site-packages/sqlalchemy/sql/type_api.py", line 359, in compare_values
    return x == y
TypeError: can't compare offset-naive and offset-aware datetimes
ERROR:root:DB Exception! can't compare offset-naive and offset-aware datetimes
127.0.0.1 - - [17/Apr/2018 11:21:07] "POST /v1/tickets HTTP/1.1" 201 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2018 11:21:07] "POST /v1/tickets HTTP/1.1" 201 -
127.0.0.1 - - [17/Apr/2018 11:21:12] "GET /v1/events/2/tickets HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2018 11:21:12] "GET /v1/events/2/tickets HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2018 11:21:34] "POST /v1/attendees/2 HTTP/1.1" 405 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2018 11:21:34] "POST /v1/attendees/2 HTTP/1.1" 405 -

**Comment by mayank8318** [comment]
@iamareebjamal I think this is the problem - `can't compare offset-naive and offset-aware datetimes`

**Comment by iamareebjamal** [comment]
No that warning is printed each time. What response did you get?

**Comment by mayank8318** [comment]
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>

**Comment by mayank8318** [comment]
URL -> localhost:5000/v1/attendees/2

BODY -> {
  "data": {
    "attributes": {
      "firstname": "John",
      "lastname": "Doe"
    },
    "type": "attendee",
    "relationships": {
      "event": {
        "data": {
          "id": "2",
          "type": "event"
        }
      },
      "ticket": {
        "data": {
          "id": "8",
          "type": "ticket"
        }
      }
    }
  }
}


TO SHOW THE AVAILABLE TICKETS :
{
    "meta": {
        "count": 3
    },
    "data": [
        {
            "relationships": {
                "ticket-tags": {
                    "links": {
                        "self": "/v1/tickets/2/relationships/ticket-tags",
                        "related": "/v1/tickets/2/ticket-tags"
                    }
                },
                "access-codes": {
                    "links": {
                        "self": "/v1/tickets/2/relationships/access-codes",
                        "related": "/v1/tickets/2/access-codes"
                    }
                },
                "attendees": {
                    "links": {
                        "self": "/v1/tickets/2/relationships/attendees",
                        "related": "/v1/attendees?ticket_id=2"
                    }
                },
                "event": {
                    "links": {
                        "self": "/v1/tickets/2/relationships/event",
                        "related": "/v1/tickets/2/event"
                    }
                }
            },
            "attributes": {
                "description": "some description",
                "type": "VIP-ticket",
                "price": 100,
                "name": "ticket-name",
                "max-order": 100,
                "is-description-visible": false,
                "is-fee-absorbed": false,
                "position": 1,
                "quantity": 100,
                "is-hidden": false,
                "sales-ends-at": "2017-06-30T00:24:47.500127+00:00",
                "min-order": 1,
                "sales-starts-at": "2017-06-01T01:24:47.500127+00:00"
            },
            "type": "ticket",
            "id": "2",
            "links": {
                "self": "/v1/tickets/2"
            }
        },
        {
            "relationships": {
                "ticket-tags": {
                    "links": {
                        "self": "/v1/tickets/6/relationships/ticket-tags",
                        "related": "/v1/tickets/6/ticket-tags"
                    }
                },
                "access-codes": {
                    "links": {
                        "self": "/v1/tickets/6/relationships/access-codes",
                        "related": "/v1/tickets/6/access-codes"
                    }
                },
                "attendees": {
                    "links": {
                        "self": "/v1/tickets/6/relationships/attendees",
                        "related": "/v1/attendees?ticket_id=6"
                    }
                },
                "event": {
                    "links": {
                        "self": "/v1/tickets/6/relationships/event",
                        "related": "/v1/tickets/6/event"
                    }
                }
            },
            "attributes": {
                "description": "some description",
                "type": "normal ticket",
                "price": 0,
                "name": "ticket-name11",
                "max-order": 100,
                "is-description-visible": false,
                "is-fee-absorbed": false,
                "position": 1,
                "quantity": 100,
                "is-hidden": false,
                "sales-ends-at": "2017-06-30T00:24:47.500127+00:00",
                "min-order": 1,
                "sales-starts-at": "2017-06-01T01:24:47.500127+00:00"
            },
            "type": "ticket",
            "id": "6",
            "links": {
                "self": "/v1/tickets/6"
            }
        },
        {
            "relationships": {
                "ticket-tags": {
                    "links": {
                        "self": "/v1/tickets/8/relationships/ticket-tags",
                        "related": "/v1/tickets/8/ticket-tags"
                    }
                },
                "access-codes": {
                    "links": {
                        "self": "/v1/tickets/8/relationships/access-codes",
                        "related": "/v1/tickets/8/access-codes"
                    }
                },
                "attendees": {
                    "links": {
                        "self": "/v1/tickets/8/relationships/attendees",
                        "related": "/v1/attendees?ticket_id=8"
                    }
                },
                "event": {
                    "links": {
                        "self": "/v1/tickets/8/relationships/event",
                        "related": "/v1/tickets/8/event"
                    }
                }
            },
            "attributes": {
                "description": "some description",
                "type": "normal ticket",
                "price": 0,
                "name": "ticket-name1",
                "max-order": 100,
                "is-description-visible": false,
                "is-fee-absorbed": true,
                "position": 1,
                "quantity": 100,
                "is-hidden": false,
                "sales-ends-at": "2017-06-30T00:24:47.500127+00:00",
                "min-order": 1,
                "sales-starts-at": "2017-06-01T01:24:47.500127+00:00"
            },
            "type": "ticket",
            "id": "8",
            "links": {
                "self": "/v1/tickets/8"
            }
        }
    ],
    "jsonapi": {
        "version": "1.0"
    },
    "links": {
        "self": "/v1/events/2/tickets"
    }
}

**Comment by iamareebjamal** [comment]
URL should not have /2

**Comment by mayank8318** [comment]
![screenshot from 2018-04-17 12-02-05](https://user-images.githubusercontent.com/22395998/38852353-279c704a-4237-11e8-9d8b-b1e6318d7ce4.png)
But the docs say there should be an event id?

**Comment by mayank8318** [comment]
@iamareebjamal Ok worked. I think the docs need to be corrected then? Also, pdf-url is a required field but the docs say otherwise?

**Comment by iamareebjamal** [comment]
pdf-url shouldn't be required

**Comment by mayank8318** [comment]
I get this if it is not specified :
{
    "errors": [
        {
            "status": "422",
            "source": {
                "pointer": "/data/attributes/pdf-url"
            },
            "detail": "Missing data for required field.",
            "title": "Validation error"
        }
    ],
    "jsonapi": {
        "version": "1.0"
    }
}

**Comment by mayank8318** [comment]
Ok should I make another issue for that or do it in this only? Also, I think PR #4666 should solve this issue though. I will try and confirm.

**Comment by iamareebjamal** [comment]
Let @shubham-padia @SaptakS @niranjan94 decide about the pdf-url

**Comment by poush** [comment]
@mayank8318 It should be optional  only as the pdf_url is filled by orders api itself after completion of order.

**Comment by iamareebjamal** [comment]
@mayank8318 Please create an issue to change pdf-url to optional

**Comment by iamareebjamal** [comment]
@mayank8318 please check if this issue can be closed

**Comment by mayank8318** [comment]
@iamareebjamal This has a different error:
![screenshot from 2018-04-17 12-26-53](https://user-images.githubusercontent.com/22395998/38884697-fb406b3a-428d-11e8-83ec-8b6b8313b66f.png)

Working on it, will send a PR soon.

**Comment by iamareebjamal** [comment]
This is not the issue. See #4645

**Comment by mayank8318** [comment]
'secret' is used for creating the hash while saving the pdf. This happens after the order is saved in the database. I think both the issues coincide. What should I do here?

**Comment by iamareebjamal** [comment]
That issue is not linked to this. Just run this command in your console

`update settings set secret = 'some_secret_key';`

**Comment by iamareebjamal** [comment]
@mayank8318 Status?

**Comment by mayank8318** [comment]
@iamareebjamal I had an exam today, so couldn't try it. I will update the PR by tonight

**Comment by mayank8318** [comment]
@iamareebjamal After updating secret in postgres, 201 is returned and the database is updated successfully.
