### ISSUE TITLE
Key error: 'user_id' when logging in the server

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-server#4692]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
When logging in the server, the server returns HTTP 500.

**Expected behavior:**
It should error out.

**Steps to reproduce:**
Try to login using your credentials.

**Related code:**

``` Python
@jwt_required
def is_user_itself(view, view_args, view_kwargs, *args, **kwargs):
    """
    Allows admin and super admin access to any resource irrespective of id.
    Otherwise the user can only access his/her resource.
    """
    user = current_identity
    if not user.is_admin and not user.is_super_admin and user.id != kwargs['user_id']:
        return ForbiddenError({'source': ''}, 'Access Forbidden').respond()
    return view(*view_args, **view_kwargs)
```

**Other information:**
``` Python
127.0.0.1 - - [03/May/2018 23:46:27] "GET /v1/users/2 HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [03/May/2018 23:46:27] "GET /v1/users/2 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/srv_twry/work/Projects/Community-Projects/Fossasia/open-event-server/app/__init__.py", line 71, in __call__
    return self.app(environ, start_response)
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/media/srv_twry/work/Projects/Community-Projects/Fossasia/open-event-server/src/flask-rest-jsonapi/flask_rest_jsonapi/api.py", line 133, in decorated
    return self.check_permissions(view, view_args, view_kwargs, *args, **kwargs)
  File "/media/srv_twry/work/Projects/Community-Projects/Fossasia/open-event-server/app/api/helpers/permission_manager.py", line 435, in permission_manager
    return permissions[args[0]](view, view_args, view_kwargs, *args, **kwargs)
  File "/media/srv_twry/work/Projects/Community-Projects/Fossasia/open-event-server/app/api/helpers/permissions.py", line 45, in decorator
    return fn(*args, **kwargs)
  File "/media/srv_twry/work/Projects/Community-Projects/Fossasia/open-event-server/app/api/helpers/permission_manager.py", line 109, in is_user_itself
    if not user.is_admin and not user.is_super_admin and user.id != kwargs['user_id']:
KeyError: 'user_id'
```

**Possible solution**

It is related to PR #4666. I changed every kwarg to ```user_id``` from ```id``` but the  ```flask_rest_jsonapi``` library sends ```id``` instead of ```user_id``` due to which we get key error when logging in. 
One solution would be to convert every instance of ```user_id``` kwarg to ```id```. Although we should try to move to using concrete functional arguments rather than kwargs as @iamareebjamal already stated in #4666 

**System information:** 

```
Your operating system
```
Ubuntu 16.04

```
output of `python --version`
```
Python 2.7.14 :: Anaconda, Inc.

cc @niranjan94 @iamareebjamal @poush

**Comment by iamareebjamal** [comment]
This is solved in #4677 but I agree with concrete methods

**Comment by bhaveshAn** [comment]
For now, I think we can modifying `user_id` to `id` should be done
taking this one.

**Comment by srv-twry** [comment]
@bhaveshAn please read the above comment. It already has an active PR IMO.

**Comment by bhaveshAn** [comment]
I guess [#4677](https://github.com/fossasia/open-event-server/issues/4677) focussing on Refactoring to Python3 @srv-twry @iamareebjamal

**Comment by iamareebjamal** [comment]
@bhaveshAn Yes it is, but it also contains fix to this error

**Comment by srv-twry** [comment]
closing this since another pr already solves this.
