### ISSUE TITLE
Nosetests fails due to multiple TypeErrors

### ISSUE THREAD

**Issue by siddhant-curious** [fossasia/open-event-server#4709]
**I'm submitting a ...**  (check one with "x")
- [ x] bug report
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server
- [ ] feature request

**Current behavior:**

Attempting to run `nosetests tests/unittests` results in following errors. 

`TypeError: can't compare offset-naive and offset-aware datetimes`

```
 File "/Users/siddhant/OpenSource/open-event/open-event-server/app/api/helpers/db.py", line 26, in save_to_db
    db.session.commit()
  File "/Users/siddhant/OpenSource/open-event/venv/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/siddhant/OpenSource/open-event/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 921, in commit
    self.transaction.commit()
  File "/Users/siddhant/OpenSource/open-event/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/Users/siddhant/OpenSource/open-event/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/Users/siddhant/OpenSource/open-event/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2192, in flush
    self._flush(objects)
  File "/Users/siddhant/OpenSource/open-event/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2312, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/siddhant/OpenSource/open-event/venv/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/siddhant/OpenSource/open-event/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2276, in _flush
    flush_context.execute()
  File "/Users/siddhant/OpenSource/open-event/venv/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/Users/siddhant/OpenSource/open-event/venv/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/Users/siddhant/OpenSource/open-event/venv/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
    mapper, table, update)
  File "/Users/siddhant/OpenSource/open-event/venv/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 659, in _emit_update_statements
    lambda rec: (
  File "/Users/siddhant/OpenSource/open-event/venv/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 485, in _collect_update_commands
    value, state.committed_state[propkey]) is not True:
  File "/Users/siddhant/OpenSource/open-event/venv/lib/python2.7/site-packages/sqlalchemy/sql/type_api.py", line 359, in compare_values
    return x == y
TypeError: can't compare offset-naive and offset-aware datetimes
```
`TypeError: argument cannot be of 'NoneType' type, must be of text type` 

```
======================================================================
ERROR: test_get_or_create (tests.unittests.api.helpers.test_db.TestDBHelperValidation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/siddhant/OpenSource/open-event/open-event-server/tests/unittests/api/helpers/test_db.py", line 46, in test_get_or_create
    obj, is_created = get_or_create(Event, name="new event", starts_at=event.starts_at, ends_at=event.ends_at)
  File "/Users/siddhant/OpenSource/open-event/open-event-server/app/api/helpers/db.py", line 62, in get_or_create
    instance = model(**kwargs)
  File "<string>", line 4, in __init__
  File "/Users/siddhant/OpenSource/open-event/venv/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 414, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/Users/siddhant/OpenSource/open-event/venv/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/siddhant/OpenSource/open-event/venv/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 411, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/Users/siddhant/OpenSource/open-event/open-event-server/app/models/event.py", line 214, in __init__
    self.description = clean_up_string(description)
  File "/Users/siddhant/OpenSource/open-event/open-event-server/app/models/event.py", line 266, in __setattr__
    super(Event, self).__setattr__(name, clean_html(clean_up_string(value)))
  File "/Users/siddhant/OpenSource/open-event/open-event-server/app/models/helpers/versioning.py", line 51, in clean_html
    cleaned = bleach.clean(html, tags=tags, attributes=attrs, styles=styles, strip=True)
  File "/Users/siddhant/OpenSource/open-event/venv/lib/python2.7/site-packages/bleach/__init__.py", line 99, in clean
    return cleaner.clean(text)
  File "/Users/siddhant/OpenSource/open-event/venv/lib/python2.7/site-packages/bleach/sanitizer.py", line 255, in clean
    raise TypeError(message)
TypeError: argument cannot be of 'NoneType' type, must be of text type
```

**Expected behavior:**
Tests should pass and execute successfully. 

**Steps to reproduce:**
Run `nosetests tests/unittests` 

**System information:** 

```
macOS High Sierra Version 10.13.14
```

```
Python 2.7.10 
```

**Comment by party98** [comment]
Please give the full stack trace for the first error: `TypeError: argument cannot be of 'NoneType' type, must be of text type`

**Comment by siddhant-curious** [comment]
@party98 it's already there

**Comment by party98** [comment]
Sorry, missed it

**Comment by schedutron** [comment]
@siddhant-curious Can I work on this issue?

**Comment by siddhant-curious** [comment]
@schedutron yeah, go ahead.

**Comment by schedutron** [comment]
When I run the tests, all of them pass:

```
schedutron (development) open-event-server $ nosetests tests/unittests/
........./usr/local/lib/python3.6/site-packages/flask/sessions.py:208: UserWarning: "localhost" is not a valid cookie domain, it must contain a ".". Add an entry to your hosts file, for example "localhost.localdomain", and use that instead.
  ' "{rv}.localdomain", and use that instead.'.format(rv=rv)
.......................................
----------------------------------------------------------------------
Ran 48 tests in 65.436s

OK
schedutron (development) open-event-server $ 
```

Maybe this is because the project is on Python3 now, and you faced this issue with Python2?

**Comment by iamareebjamal** [comment]
Yes, this is because of running it on Python2
