### ISSUE TITLE
HTTP 500 on GET user notifications

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-server#4722]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
The dev server returns HTTP 500 on trying to fetch the user details using the id.

**Expected behavior:**
It should return the user details.

**Steps to reproduce:**
Make a get request to the ```{{url}}/v1/users/{{user_id}}``` endpoint where url = https://open-event-api-dev.herokuapp.com and user_id = your user id. 

![image](https://user-images.githubusercontent.com/21277837/39965808-d1d8f16a-56bd-11e8-83d2-22fab635915f.png)

**Would you like to work on it ?**
Yes on it.

**Comment by srv-twry** [comment]
On the local server, the get user details works fine strangely, but the server errors out when getting the user notifications.

``` Python
127.0.0.1 - - [13/May/2018 15:36:31] "GET /v1/users/2 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [13/May/2018 15:36:31] "GET /v1/users/2 HTTP/1.1" 200 -
127.0.0.1 - - [13/May/2018 15:36:32] "OPTIONS /v1/users/2/notifications?filter=%5B%7B%22name%22%3A%22is-read%22%2C%22op%22%3A%22eq%22%2C%22val%22%3Afalse%7D%5D&sort=-received-at HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [13/May/2018 15:36:32] "OPTIONS /v1/users/2/notifications?filter=%5B%7B%22name%22%3A%22is-read%22%2C%22op%22%3A%22eq%22%2C%22val%22%3Afalse%7D%5D&sort=-received-at HTTP/1.1" 200 -
127.0.0.1 - - [13/May/2018 15:36:32] "GET /v1/users/2/notifications?filter=%5B%7B%22name%22%3A%22is-read%22%2C%22op%22%3A%22eq%22%2C%22val%22%3Afalse%7D%5D&sort=-received-at HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [13/May/2018 15:36:32] "GET /v1/users/2/notifications?filter=%5B%7B%22name%22%3A%22is-read%22%2C%22op%22%3A%22eq%22%2C%22val%22%3Afalse%7D%5D&sort=-received-at HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/srv_twry/work/Projects/Community-Projects/Fossasia/open-event-server/app/__init__.py", line 64, in __call__
    return self.app(environ, start_response)
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/media/srv_twry/work/Projects/Community-Projects/Fossasia/open-event-server/src/flask-rest-jsonapi/flask_rest_jsonapi/api.py", line 133, in decorated
    return self.check_permissions(view, view_args, view_kwargs, *args, **kwargs)
  File "/media/srv_twry/work/Projects/Community-Projects/Fossasia/open-event-server/app/api/helpers/permission_manager.py", line 435, in permission_manager
    return permissions[args[0]](view, view_args, view_kwargs, *args, **kwargs)
  File "/media/srv_twry/work/Projects/Community-Projects/Fossasia/open-event-server/app/api/helpers/permissions.py", line 45, in decorator
    return fn(*args, **kwargs)
  File "/media/srv_twry/work/Projects/Community-Projects/Fossasia/open-event-server/app/api/helpers/permission_manager.py", line 109, in is_user_itself
    if not user.is_admin and not user.is_super_admin and user.id != kwargs['user_id']:
KeyError: 'user_id'
```
