### ISSUE TITLE
HTTP 500 on uploading a cropped "Event Image"

### ISSUE THREAD

**Issue by mayank8318** [fossasia/open-event-server#4732]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
Error 500 occurs when you try to upload a cropped image. 

**Expected behavior:**
Image URL should be added to the server successfully.

**Steps to reproduce:**
Go to create an event in the frontend
Add image for "Event Image"
Press on Forward

**Related code:**

```
INFO:werkzeug:127.0.0.1 - - [15/May/2018 15:44:39] "PATCH /v1/events/148c2f40 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/mayank/OpenSource/open-event-server/app/__init__.py", line 64, in __call__
    return self.app(environ, start_response)
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mayank/OpenSource/open-event-server/src/flask-rest-jsonapi/flask_rest_jsonapi/api.py", line 133, in decorated
    return self.check_permissions(view, view_args, view_kwargs, *args, **kwargs)
  File "/home/mayank/OpenSource/open-event-server/app/api/helpers/permission_manager.py", line 435, in permission_manager
    return permissions[args[0]](view, view_args, view_kwargs, *args, **kwargs)
  File "/home/mayank/OpenSource/open-event-server/app/api/helpers/permissions.py", line 45, in decorator
    return fn(*args, **kwargs)
  File "/home/mayank/OpenSource/open-event-server/app/api/helpers/permission_manager.py", line 58, in is_coorganizer
    return view(*view_args, **view_kwargs)
  File "/home/mayank/OpenSource/open-event-server/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/mayank/OpenSource/open-event-server/src/flask-rest-jsonapi/flask_rest_jsonapi/resource.py", line 68, in dispatch_request
    response = method(*args, **kwargs)
  File "/home/mayank/OpenSource/open-event-server/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 56, in wrapper
    return func(*args, **kwargs)
  File "/home/mayank/OpenSource/open-event-server/src/flask-rest-jsonapi/flask_rest_jsonapi/resource.py", line 300, in patch
    self._data_layer.update_object(obj, data, kwargs)
  File "/home/mayank/OpenSource/open-event-server/src/flask-rest-jsonapi/flask_rest_jsonapi/data_layers/alchemy.py", line 126, in update_object
    self.before_update_object(obj, data, view_kwargs)
  File "/home/mayank/OpenSource/open-event-server/app/api/events.py", line 382, in before_update_object
    uploaded_images = create_save_image_sizes(data['original_image_url'], 'event', event.id)
  File "/home/mayank/OpenSource/open-event-server/app/api/helpers/files.py", line 163, in create_save_image_sizes
    'original_image_url': create_save_resized_image(image_file, 0, 0, 0, original_upload_path, resize=False),
  File "/home/mayank/OpenSource/open-event-server/app/api/helpers/files.py", line 78, in create_save_resized_image
    data = urllib.request.urlopen(image_file).read()
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
```

**Other information:**

**System information:** 

```
Ubuntu 18.04
```

```
Python 3
```

**Comment by mayank8318** [comment]
@niranjan94 @SaptakS This is happening because the server cannot read from the localhost file location and can be closed
