### ISSUE TITLE
GET request to notifications of a user results in 500

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#4742]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

Heroku Error log Trace:
```js
2018-05-17T14:59:04.104222+00:00 app[web.1]: Exception on /v1/users/152/notifications [GET]
2018-05-17T14:59:04.104224+00:00 app[web.1]: Traceback (most recent call last):
2018-05-17T14:59:04.104226+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
2018-05-17T14:59:04.104227+00:00 app[web.1]:     response = self.full_dispatch_request()
2018-05-17T14:59:04.104229+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
2018-05-17T14:59:04.104231+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2018-05-17T14:59:04.104232+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
2018-05-17T14:59:04.104234+00:00 app[web.1]:     return cors_after_request(app.make_response(f(*args, **kwargs)))
2018-05-17T14:59:04.104236+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
2018-05-17T14:59:04.104237+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2018-05-17T14:59:04.104239+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
2018-05-17T14:59:04.104241+00:00 app[web.1]:     raise value
2018-05-17T14:59:04.104243+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
2018-05-17T14:59:04.104245+00:00 app[web.1]:     rv = self.dispatch_request()
2018-05-17T14:59:04.104246+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
2018-05-17T14:59:04.104248+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2018-05-17T14:59:04.104250+00:00 app[web.1]:   File "/app/.heroku/src/flask-rest-jsonapi/flask_rest_jsonapi/api.py", line 133, in decorated
2018-05-17T14:59:04.104251+00:00 app[web.1]:     return self.check_permissions(view, view_args, view_kwargs, *args, **kwargs)
2018-05-17T14:59:04.104253+00:00 app[web.1]:   File "/app/app/api/helpers/permission_manager.py", line 435, in permission_manager
2018-05-17T14:59:04.104255+00:00 app[web.1]:     return permissions[args[0]](view, view_args, view_kwargs, *args, **kwargs)
2018-05-17T14:59:04.104256+00:00 app[web.1]:   File "/app/app/api/helpers/permissions.py", line 45, in decorator
2018-05-17T14:59:04.104275+00:00 app[web.1]:     return fn(*args, **kwargs)
2018-05-17T14:59:04.104277+00:00 app[web.1]:   File "/app/app/api/helpers/permission_manager.py", line 109, in is_user_itself
2018-05-17T14:59:04.104278+00:00 app[web.1]:     if not user.is_admin and not user.is_super_admin and user.id != kwargs['user_id']:
2018-05-17T14:59:04.104280+00:00 app[web.1]: KeyError: 'user_id'
```

**Comment by srv-twry** [comment]
Duplicate of #4722

**Comment by srv-twry** [comment]
@CosmicCoder96 It will be resolved as soon as my PR is merged.

**Comment by CosmicCoder96** [comment]
@srv-twry Thanks it's fixed !!
