### ISSUE TITLE
HTTP 500 on Event copy task

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-server#4826]
**Describe the bug**

When trying to use Event copy to copy the event, the server errors out and sends HTTP 500. 

**To Reproduce**
1. Use the endpoint to copy an event.

**Expected behavior**

It shouldn't error out.

**Stacktrace**

```
127.0.0.1 - - [01/Jun/2018 02:34:18] "POST /v1/events/8c1f5609/copy? HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [01/Jun/2018 02:34:18] "POST /v1/events/8c1f5609/copy? HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/srv_twry/work/Projects/Community-Projects/Fossasia/open-event-server/app/__init__.py", line 64, in __call__
    return self.app(environ, start_response)
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/media/srv_twry/work/Projects/Community-Projects/Fossasia/open-event-server/app/api/event_copy.py", line 74, in create_event_copy
    logo_url = create_save_resized_image(image_file=sponsor.logo_url, resize=False)
  File "/media/srv_twry/work/Projects/Community-Projects/Fossasia/open-event-server/app/api/helpers/files.py", line 78, in create_save_resized_image
    data = urllib.request.urlopen(image_file).read()
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/urllib/request.py", line 517, in open
    req.timeout = timeout
AttributeError: 'NoneType' object has no attribute 'timeout'

```

**Comment by schedutron** [comment]
This might be the error in `urllib` library itself? Maybe we should use the `requests` library for reading the image in `helpers/files.py`?

**Comment by bhaveshAn** [comment]
wanna work on it

**Comment by srv-twry** [comment]
cool, go ahead.

**Comment by srv-twry** [comment]
@schedutron Yes i also think so. Let's use requests.

**Comment by bhaveshAn** [comment]
@srv-twry @schedutron 
POST `/v1/events/1/copy`
gives me 
{
	"copied": true,
	"id": 2,
	"identifier": "efa1589d"
}

**Comment by srv-twry** [comment]
Ok so you made any changes ?

**Comment by bhaveshAn** [comment]
No its already working.

**Comment by srv-twry** [comment]
@bhaveshAn If you aren't able to reproduce then I can take this one.

**Comment by bhaveshAn** [comment]
>  If you aren't able to reproduce then I can take this one.

Sure
