### ISSUE TITLE
HTTP 500 on creating an event

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-server#4871]
**Describe the bug**

The server  returns HTTP 500 when creating or patching an event.

```
{
  "data": {
    "attributes": {
      "original-image-url": "https://media.licdn.com/media/AAEAAQAAAAAAAAdcAAAAJDNkMjFlMTNmLTNjMTMtNGRmNS04OTUwLTEwMzc2NzNhZDIxOA.png",
      "logo-url": "https://events.google.com/io2016/images/touch/homescreen192.png"
    },
    "id": "{{event}}",
    "type": "event"
  }
}
```

**To Reproduce**
1. Make a PATCH request with the data above.

**Expected behavior**

It should be successfully created or updated.

**Stacktrace**

```
Traceback (most recent call last):
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/srv_twry/work/Projects/Community-Projects/Fossasia/open-event-server/app/__init__.py", line 64, in __call__
    return self.app(environ, start_response)
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/media/srv_twry/work/Projects/Community-Projects/Fossasia/open-event-server/src/flask-rest-jsonapi/flask_rest_jsonapi/api.py", line 133, in decorated
    return self.check_permissions(view, view_args, view_kwargs, *args, **kwargs)
  File "/media/srv_twry/work/Projects/Community-Projects/Fossasia/open-event-server/app/api/helpers/permission_manager.py", line 431, in permission_manager
    return permissions[args[0]](view, view_args, view_kwargs, *args, **kwargs)
  File "/media/srv_twry/work/Projects/Community-Projects/Fossasia/open-event-server/app/api/helpers/permissions.py", line 45, in decorator
    return fn(*args, **kwargs)
  File "/media/srv_twry/work/Projects/Community-Projects/Fossasia/open-event-server/app/api/helpers/permission_manager.py", line 61, in is_coorganizer
    return view(*view_args, **view_kwargs)
  File "/media/srv_twry/work/Projects/Community-Projects/Fossasia/open-event-server/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/media/srv_twry/work/Projects/Community-Projects/Fossasia/open-event-server/src/flask-rest-jsonapi/flask_rest_jsonapi/resource.py", line 68, in dispatch_request
    response = method(*args, **kwargs)
  File "/media/srv_twry/work/Projects/Community-Projects/Fossasia/open-event-server/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 56, in wrapper
    return func(*args, **kwargs)
  File "/media/srv_twry/work/Projects/Community-Projects/Fossasia/open-event-server/src/flask-rest-jsonapi/flask_rest_jsonapi/resource.py", line 300, in patch
    self._data_layer.update_object(obj, data, kwargs)
  File "/media/srv_twry/work/Projects/Community-Projects/Fossasia/open-event-server/src/flask-rest-jsonapi/flask_rest_jsonapi/data_layers/alchemy.py", line 126, in update_object
    self.before_update_object(obj, data, view_kwargs)
  File "/media/srv_twry/work/Projects/Community-Projects/Fossasia/open-event-server/app/api/events.py", line 423, in before_update_object
    uploaded_images = create_save_image_sizes(data['original_image_url'], 'event', event.id)
  File "/media/srv_twry/work/Projects/Community-Projects/Fossasia/open-event-server/app/api/helpers/files.py", line 166, in create_save_image_sizes
    'original_image_url': create_save_resized_image(image_file, 0, 0, 0, original_upload_path, resize=False),
  File "/media/srv_twry/work/Projects/Community-Projects/Fossasia/open-event-server/app/api/helpers/files.py", line 81, in create_save_resized_image
    data = urllib.request.urlopen(image_file).read()
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/srv_twry/anaconda3/envs/open-event-server/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by srv-twry** [comment]
@schedutron @bhaveshAn @mayank8318 You may claim it if you want. I already have enough issues to work on. :)

**Comment by bhaveshAn** [comment]
@srv-twry Its because your passed value for `original-image-url` isn't showing any image https://media.licdn.com/media/AAEAAQAAAAAAAAdcAAAAJDNkMjFlMTNmLTNjMTMtNGRmNS04OTUwLTEwMzc2NzNhZDIxOA.png

try with this value or some other :)
```
 "original-image-url": "https://www.cdacentre.com/wp-content/uploads/2017/10/event.jpg",
```

**Comment by srv-twry** [comment]
Yes, I know. I did it on purpose. The server should handle these cases as well. It should never return HTTP 500 in any case. If there is a problem with the image, then it should atleast return 422 unprocessable entity. 
We have easily achieve it by adding a try except block IMO.

**Comment by bhaveshAn** [comment]
Try except is handling IOERROR for reading the image and not for HTTPError 
Working on it
