### ISSUE TITLE
docker build failing

### ISSUE THREAD

**Issue by surajnarwade** [fossasia/open-event-server#4892]
```
$ docker-compose build
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 7, in <module>
    from compose.cli.main import main
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 20, in <module>
    from ..bundle import get_image_digests
  File "/usr/lib/python2.7/site-packages/compose/bundle.py", line 12, in <module>
    from .config.serialize import denormalize_config
  File "/usr/lib/python2.7/site-packages/compose/config/__init__.py", line 6, in <module>
    from .config import ConfigurationError
  File "/usr/lib/python2.7/site-packages/compose/config/config.py", line 12, in <module>
    import yaml
ImportError: No module named yaml
```

**Comment by srv-twry** [comment]
Not sure if this issue is valid or not now. We have shifted to python 3.6. Closing this. Please reopen if necessary.
