### ISSUE TITLE
Celery stops working when elastic search is enabled

### ISSUE THREAD

**Issue by mayank8318** [fossasia/open-event-server#5358]
**Describe the bug**
If the elastic search is enabled via `ENABLE_ELASTICSEARCH=true` in the .env file, Celery crashes.

**To Reproduce**
1. Enable elastic search by copying `ENABLE_ELASTICSEARCH=true
ELASTICSEARCH_HOST=localhost:9200` lines into your .env file
2. Start celery 

**Expected behavior**
It should work properly

**Stacktrace**
```sh
[2018-08-16 09:59:00,205: ERROR/MainProcess] Task rebuild.events.elasticsearch[92c3806a-ca95-42d1-ac19-573c0183b261] raised unexpected: RequestError(400, 'mapper_parsing_exception', {'error': {'root_cause': [{'type': 'mapper_parsing_exception', 'reason': 'No handler for type [text] declared on field [location_name]'}], 'type': 'mapper_parsing_exception', 'reason': 'Failed to parse mapping [doc]: No handler for type [text] declared on field [location_name]', 'caused_by': {'type': 'mapper_parsing_exception', 'reason': 'No handler for type [text] declared on field [location_name]'}}, 'status': 400})
Traceback (most recent call last):
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/mayank/OpenSource/open-event-server/app/views/elastic_cron_helpers.py", line 20, in cron_rebuild_events_elasticsearch
    rebuild_indices(client=elastic)
  File "/home/mayank/OpenSource/open-event-server/app/models/search/sync.py", line 45, in rebuild_indices
    index_class.init()
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/elasticsearch_dsl/document.py", line 161, in init
    cls._doc_type.init(index, using)
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/elasticsearch_dsl/document.py", line 85, in init
    self.mapping.save(index or self.index, using=using or self.using)
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/elasticsearch_dsl/mapping.py", line 116, in save
    return index.save()
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/elasticsearch_dsl/index.py", line 219, in save
    return self.create()
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/elasticsearch_dsl/index.py", line 203, in create
    self.connection.indices.create(index=self._name, body=self.to_dict(), **kwargs)
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/elasticsearch/client/indices.py", line 91, in create
    params=params, body=body)
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 185, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'mapper_parsing_exception', 'No handler for type [text] declared on field [location_name]')
[2018-08-16 09:59:00,206: ERROR/MainProcess] Task rebuild.events.elasticsearch[72c53458-a2b3-4145-9d2f-2a6b171bc8ed] raised unexpected: RequestError(400, 'mapper_parsing_exception', {'error': {'root_cause': [{'type': 'mapper_parsing_exception', 'reason': 'No handler for type [text] declared on field [location_name]'}], 'type': 'mapper_parsing_exception', 'reason': 'Failed to parse mapping [doc]: No handler for type [text] declared on field [location_name]', 'caused_by': {'type': 'mapper_parsing_exception', 'reason': 'No handler for type [text] declared on field [location_name]'}}, 'status': 400})
Traceback (most recent call last):
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/mayank/OpenSource/open-event-server/app/views/elastic_cron_helpers.py", line 20, in cron_rebuild_events_elasticsearch
    rebuild_indices(client=elastic)
  File "/home/mayank/OpenSource/open-event-server/app/models/search/sync.py", line 45, in rebuild_indices
    index_class.init()
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/elasticsearch_dsl/document.py", line 161, in init
    cls._doc_type.init(index, using)
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/elasticsearch_dsl/document.py", line 85, in init
    self.mapping.save(index or self.index, using=using or self.using)
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/elasticsearch_dsl/mapping.py", line 116, in save
    return index.save()
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/elasticsearch_dsl/index.py", line 219, in save
    return self.create()
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/elasticsearch_dsl/index.py", line 203, in create
    self.connection.indices.create(index=self._name, body=self.to_dict(), **kwargs)
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/elasticsearch/client/indices.py", line 91, in create
    params=params, body=body)
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 185, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'mapper_parsing_exception', 'No handler for type [text] declared on field [location_name]')

```

**Additional details (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python Version 3.6

**Comment by prateekj117** [comment]
@mayank8318 @iamareebjamal Is this issue still open? I would like to work on it.

**Comment by CosmicCoder96** [comment]
Not implementing elastic search as of now.
