### ISSUE TITLE
Loading admin/users throws 404

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-server#5661]
**Describe the bug**

Clicking on Admin/Users throws a 404 error screen
![image](https://user-images.githubusercontent.com/21087061/53804556-d5a73100-3f6d-11e9-9b14-cd10d1485266.png)

**To Reproduce**
1. Go to Admin/Users
2. See error

**Expected behavior**

Normal User lists should've load up instead of a 404

**Stacktrace**

```
Traceback (most recent call last):
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/uddeshya/Desktop/mySetup/open-event-server/app/__init__.py", line 67, in __call__
    return self.app(environ, start_response)
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/uddeshya/venv/src/flask-rest-jsonapi/flask_rest_jsonapi/api.py", line 133, in decorated
    return self.check_permissions(view, view_args, view_kwargs, *args, **kwargs)
  File "/home/uddeshya/Desktop/mySetup/open-event-server/app/api/helpers/permission_manager.py", line 439, in permission_manager
    return permissions[args[0]](view, view_args, view_kwargs, *args, **kwargs)
  File "/home/uddeshya/Desktop/mySetup/open-event-server/app/api/helpers/permissions.py", line 45, in decorator
    return fn(*args, **kwargs)
  File "/home/uddeshya/Desktop/mySetup/open-event-server/app/api/helpers/permission_manager.py", line 38, in is_admin
    return view(*view_args, **view_kwargs)
  File "/home/uddeshya/venv/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/uddeshya/venv/src/flask-rest-jsonapi/flask_rest_jsonapi/resource.py", line 68, in dispatch_request
    response = method(*args, **kwargs)
  File "/home/uddeshya/venv/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 56, in wrapper
    return func(*args, **kwargs)
  File "/home/uddeshya/venv/src/flask-rest-jsonapi/flask_rest_jsonapi/resource.py", line 161, in get
    url_for(self.view, **view_kwargs))
  File "/home/uddeshya/venv/src/flask-rest-jsonapi/flask_rest_jsonapi/pagination.py", line 53, in add_pagination_links
    data['links'] = links
TypeError: list indices must be integers or slices, not str

```
**Additional details (please complete the following information):**
 - OS: [e.g. MacOS, Ubuntu, CentOS] Ubuntu 16.04 LTS
 - Python Version [e.g. `3.5`, `3.6`] 3.5

**Additional context**

I am working on it

**Comment by CosmicCoder96** [comment]
@uds5501 a pointer: I have seen this before, usually occurs when marshmallow validation fails.

**Comment by uds5501** [comment]
@CosmicCoder96 Thanks for the pointer!

**Comment by uds5501** [comment]
@CosmicCoder96 @iamareebjamal I have a work around which is not exactly removing the 404 from the front end but is somewhat working without an error as an API

The modifications I did were : 
```python
# in flask_rest_jsonapi/pagination.py

if type(data) == type([]):
        temp = {}
        temp['data'] = data
        data = temp
    data['links'] = links
```
and 
```python

# in flask_rest_jsonapi/resource.py line 162
if type(result) == type([]):
            result = result[0]
        result.update({'meta': {'count': objects_count}})

```
after these modifications, the request `http://127.0.0.1:5000/v1/users?page[size]=10&get_trashed=true&filter=[]` 
is giving me 
```json

{
    "alternate_emails": {
        "links": {
            "related": "/v1/users/2/alternate-emails",
            "self": "/v1/users/2/relationships/alternate-emails"
        }
    },
    "deleted_at": null,
    "registrar_events": {
        "links": {
            "related": "/v1/events",
            "self": "/v1/users/2/relationships/registrar-events"
        }
    },
    "email": "uds@email.com",
    "google_plus_url": null,
    "is_super_admin": true,
    "facebook_url": null,
    "avatar_url": null,
    "is_user_registrar": false,
    "is_user_organizer": true,
    "notifications": {
        "links": {
            "related": "/v1/users/2/notifications",
            "self": "/v1/users/2/relationships/notifications"
        }
    },
    "thumbnail_image_url": null,
    "favourite_events": {
        "links": {
            "related": "/v1/users/2/user-favourite-events",
            "self": "/v1/users/2/relationships/favourite-events"
        }
    },
    "details": null,
    "access_codes": {
        "links": {
            "related": "/v1/users/2/access-codes",
            "self": "/v1/users/2/relationships/access-codes"
        }
    },
    "sessions": {
        "links": {
            "related": "/v1/users/2/sessions",
            "self": "/v1/users/2/relationships/sessions"
        }
    },
    "orders": {
        "links": {
            "related": "/v1/users/2/orders",
            "self": "/v1/users/2/relationships/orders"
        }
    },
    "is_user_moderator": false,
    "organizer_events": {
        "links": {
            "related": "/v1/events",
            "self": "/v1/users/2/relationships/organizer-events"
        }
    },
    "speakers": {
        "links": {
            "related": "/v1/users/2/speakers",
            "self": "/v1/users/2/relationships/speakers"
        }
    },
    "moderator_events": {
        "links": {
            "related": "/v1/events",
            "self": "/v1/users/2/relationships/moderator-events"
        }
    },
    "instagram_url": null,
    "was_registered_with_order": false,
    "coorganizer_events": {
        "links": {
            "related": "/v1/events",
            "self": "/v1/users/2/relationships/coorganizer-events"
        }
    },
    "track_organizer_events": {
        "links": {
            "related": "/v1/events",
            "self": "/v1/users/2/relationships/track-organizer-events"
        }
    },
    "last_accessed_at": "2019-03-06T04:33:01.932575+00:00",
    "marketer_events": {
        "links": {
            "related": "/v1/events",
            "self": "/v1/users/2/relationships/marketer-events"
        }
    },
    "is_user_track_organizer": false,
    "small_image_url": null,
    "created_at": "2019-03-01T07:46:55.856616+00:00",
    "is_verified": true,
    "meta": {
        "count": 5
    },
    "is_admin": true,
    "is_sales_admin": false,
    "id": "2",
    "original_image_url": null,
    "icon_image_url": null,
    "is_user_coorganizer": false,
    "facebook_id": null,
    "is_marketer": false,
    "attendees": {
        "links": {
            "related": "/v1/users/2/attendees",
            "self": "/v1/users/2/relationships/attendees"
        }
    },
    "contact": null,
    "first_name": null,
    "sales_admin_events": {
        "links": {
            "related": "/v1/events",
            "self": "/v1/users/2/relationships/sales-admin-events"
        }
    },
    "last_name": null,
    "is_user_attendee": false,
    "email_notifications": {
        "links": {
            "related": "/v1/users/2/email-notifications",
            "self": "/v1/users/2/relationships/email-notifications"
        }
    },
    "twitter_url": null,
    "jsonapi": {
        "version": "1.0"
    },
    "discount_codes": {
        "links": {
            "related": "/v1/users/2/discount-codes",
            "self": "/v1/users/2/relationships/discount-codes"
        }
    },
    "events": {
        "links": {
            "related": "/v1/users/2/events",
            "self": "/v1/users/2/relationships/events"
        }
    }
}
```

**Comment by uds5501** [comment]
but the front-end is still throwing a 404

**Comment by CosmicCoder96** [comment]
no you don't modify the library, clear your database, and new users, the issue shouldn't persist.
