### ISSUE TITLE
Getting 404 error after creation of events

### ISSUE THREAD

**Issue by prabhupant** [fossasia/open-event-server#5710]
**Describe the bug**

404 error page is displayed right after the creation of event

**To Reproduce**
1. start creating an event
2. complete the info
3. publish the event and see the error page

**Expected behavior**

this page shouldn't be displayed. The user should be taken to the homepage

**Stacktrace**

```
Traceback (most recent call last):
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: relation "sessions_speakers_links" does not exist
LINE 3: FROM sessions_speakers_links 
             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/prabhu/Desktop/open-event-server/app/__init__.py", line 67, in __call__
    return self.app(environ, start_response)
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/prabhu/Desktop/open-event-server/venv/src/flask-rest-jsonapi/flask_rest_jsonapi/api.py", line 133, in decorated
    return self.check_permissions(view, view_args, view_kwargs, *args, **kwargs)
  File "/home/prabhu/Desktop/open-event-server/app/api/helpers/permission_manager.py", line 439, in permission_manager
    return permissions[args[0]](view, view_args, view_kwargs, *args, **kwargs)
  File "/home/prabhu/Desktop/open-event-server/app/api/helpers/permissions.py", line 45, in decorator
    return fn(*args, **kwargs)
  File "/home/prabhu/Desktop/open-event-server/app/api/helpers/permission_manager.py", line 59, in is_coorganizer
    return view(*view_args, **view_kwargs)
  File "/home/prabhu/Desktop/open-event-server/venv/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/prabhu/Desktop/open-event-server/venv/src/flask-rest-jsonapi/flask_rest_jsonapi/resource.py", line 68, in dispatch_request
    response = method(*args, **kwargs)
  File "/home/prabhu/Desktop/open-event-server/venv/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 56, in wrapper
    return func(*args, **kwargs)
  File "/home/prabhu/Desktop/open-event-server/venv/src/flask-rest-jsonapi/flask_rest_jsonapi/resource.py", line 248, in get
    result = schema.dump(obj).data
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/marshmallow/schema.py", line 511, in dump
    **kwargs
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/marshmallow/marshalling.py", line 147, in serialize
    index=(index if index_errors else None)
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/marshmallow/marshalling.py", line 68, in call_and_store
    value = getter_func(data)
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/marshmallow/marshalling.py", line 141, in <lambda>
    getter = lambda d: field_obj.serialize(attr_name, d, accessor=accessor)
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/marshmallow/fields.py", line 252, in serialize
    return self._serialize(value, attr, obj)
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/marshmallow/fields.py", line 1201, in _serialize
    return method(obj)
  File "/home/prabhu/Desktop/open-event-server/app/api/schema/event_statistics.py", line 58, in speakers_count
    accepted = self.speakers_count_type(obj=obj, state='accepted')
  File "/home/prabhu/Desktop/open-event-server/app/api/schema/event_statistics.py", line 55, in speakers_count_type
    return SessionsSpeakersLink.query.filter_by(event_id=obj.id, session_state=state).count()
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 3089, in count
    return self.from_self(col).scalar()
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2843, in scalar
    ret = self.one()
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2814, in one
    ret = self.one_or_none()
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2784, in one_or_none
    ret = list(self)
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/prabhu/Desktop/open-event-server/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "sessions_speakers_links" does not exist
LINE 3: FROM sessions_speakers_links 
             ^
 [SQL: 'SELECT count(*) AS count_1 \nFROM (SELECT sessions_speakers_links.deleted_at AS sessions_speakers_links_deleted_at, sessions_speakers_links.id AS sessions_speakers_links_id, sessions_speakers_links.event_id AS sessions_speakers_links_event_id, sessions_speakers_links.session_id AS sessions_speakers_links_session_id, sessions_speakers_links.speaker_id AS sessions_speakers_links_speaker_id, sessions_speakers_links.session_state AS sessions_speakers_links_session_state \nFROM sessions_speakers_links \nWHERE sessions_speakers_links.event_id = %(event_id_1)s AND sessions_speakers_links.session_state = %(session_state_1)s) AS anon_1'] [parameters: {'event_id_1': 6, 'session_state_1': 'accepted'}]
```

**Additional details (please complete the following information):**
 - OS: [e.g. MacOS, Ubuntu, CentOS]
 - Python Version [e.g. `3.5`, `3.6`]
 - `HEAD` Commit hash [e.g. `4629c62`]

**Screenshot of the issue**
![error](https://user-images.githubusercontent.com/19776278/54880590-2a064800-4e6c-11e9-84b2-9756f970e563.png)

**Additional context**

i'm working on it

**Comment by iamareebjamal** [comment]
Have you ran the migrations?

**Comment by prabhupant** [comment]
I forgot to run the migrations. Works fine now. Thanks :smile:
