### ISSUE TITLE
Saving draft with only event name gives 500 error

### ISSUE THREAD

**Issue by Haider8** [fossasia/open-event-server#5717]
**Describe the bug**

When draft is saved with only event name, success message is shown (```Your event has been saved```) and then the error (see the screenshot)

![draft-500-error](https://user-images.githubusercontent.com/43299408/55014045-52c74280-5010-11e9-885d-e66f825c861e.png) 

**To Reproduce**
1. Go to 'Create Event' page.
2. Enter 'event name'.
3. Click on 'Save draft'.
4. See error.

**Expected behavior**

Should have shown statistics.

**Stacktrace**

```
Traceback (most recent call last):
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/haider/github-repos/open-event-server/app/__init__.py", line 68, in __call__
    return self.app(environ, start_response)
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/haider/github-repos/open-event-server/.venv/src/flask-rest-jsonapi/flask_rest_jsonapi/api.py", line 133, in decorated
    return self.check_permissions(view, view_args, view_kwargs, *args, **kwargs)
  File "/home/haider/github-repos/open-event-server/app/api/helpers/permission_manager.py", line 439, in permission_manager
    return permissions[args[0]](view, view_args, view_kwargs, *args, **kwargs)
  File "/home/haider/github-repos/open-event-server/app/api/helpers/permissions.py", line 45, in decorator
    return fn(*args, **kwargs)
  File "/home/haider/github-repos/open-event-server/app/api/helpers/permission_manager.py", line 59, in is_coorganizer
    return view(*view_args, **view_kwargs)
  File "/home/haider/github-repos/open-event-server/.venv/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/haider/github-repos/open-event-server/.venv/src/flask-rest-jsonapi/flask_rest_jsonapi/resource.py", line 68, in dispatch_request
    response = method(*args, **kwargs)
  File "/home/haider/github-repos/open-event-server/.venv/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 56, in wrapper
    return func(*args, **kwargs)
  File "/home/haider/github-repos/open-event-server/.venv/src/flask-rest-jsonapi/flask_rest_jsonapi/resource.py", line 248, in get
    result = schema.dump(obj).data
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/marshmallow/schema.py", line 511, in dump
    **kwargs
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/marshmallow/marshalling.py", line 147, in serialize
    index=(index if index_errors else None)
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/marshmallow/marshalling.py", line 68, in call_and_store
    value = getter_func(data)
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/marshmallow/marshalling.py", line 141, in <lambda>
    getter = lambda d: field_obj.serialize(attr_name, d, accessor=accessor)
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/marshmallow/fields.py", line 252, in serialize
    return self._serialize(value, attr, obj)
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/marshmallow/fields.py", line 1201, in _serialize
    return method(obj)
  File "/home/haider/github-repos/open-event-server/app/api/schema/event_statistics.py", line 58, in speakers_count
    accepted = self.speakers_count_type(obj=obj, state='accepted')
  File "/home/haider/github-repos/open-event-server/app/api/schema/event_statistics.py", line 55, in speakers_count_type
    return SessionsSpeakersLink.query.filter_by(event_id=obj.id, session_state=state).count()
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3089, in count
    return self.from_self(col).scalar()
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2843, in scalar
    ret = self.one()
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2814, in one
    ret = self.one_or_none()
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2784, in one_or_none
    ret = list(self)
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "sessions_speakers_links" does not exist
LINE 3: FROM sessions_speakers_links 
             ^
 [SQL: 'SELECT count(*) AS count_1 \nFROM (SELECT sessions_speakers_links.deleted_at AS sessions_speakers_links_deleted_at, sessions_speakers_links.id AS sessions_speakers_links_id, sessions_speakers_links.event_id AS sessions_speakers_links_event_id, sessions_speakers_links.session_id AS sessions_speakers_links_session_id, sessions_speakers_links.speaker_id AS sessions_speakers_links_speaker_id, sessions_speakers_links.session_state AS sessions_speakers_links_session_state \nFROM sessions_speakers_links \nWHERE sessions_speakers_links.event_id = %(event_id_1)s AND sessions_speakers_links.session_state = %(session_state_1)s) AS anon_1'] [parameters: {'event_id_1': 59, 'session_state_1': 'accepted'}]
```

**Additional details (please complete the following information):**
 - OS: [e.g. MacOS, Ubuntu, CentOS]
 - Python Version [e.g. `3.5`, `3.6`]
 - `HEAD` Commit hash [e.g. `4629c62`]

**Additional context**

Willing to work on this

**Comment by Haider8** [comment]
@uds5501 Can you please confirm this issue.

**Comment by prateekj117** [comment]
@Haider8 Run migrations and try again.

**Comment by Haider8** [comment]
@prateekj117 This is giving me the error
```
(.venv) haider (development) open-event-server $ python manage.py db migrate
ERROR [root] Error: Can't locate revision identified by '24e742dae33f'
```

**Comment by prateekj117** [comment]
@Haider8 Update migrations and see if it also shows any error. If it does, I would suggest deleting the databases and making a new one again, I ran into the same error and this worked for me.

**Comment by mrsaicharan1** [comment]
@Haider8 Sync the database using ` python manage.py db upgrade`
