### ISSUE TITLE
500 Internal Server Error: Getting Speakers-Call Details 

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-server#5795]
**Describe the bug**
An internal server error is thrown when the ID of an event is requested along with the speakers call details.

**To Reproduce**
On the following request

`speakers-calls/1?include=event&fields[event]=id`

**Expected behavior**

**Stacktrace**
`Traceback (most recent call last):
  File "/home/sai/.local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/sai/Desktop/fossasia/open-event-server/app/__init__.py", line 67, in __call__
    return self.app(environ, start_response)
  File "/home/sai/.local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/sai/.local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/sai/.local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/sai/.local/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sai/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/sai/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sai/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sai/.local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/sai/.local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/sai/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sai/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/sai/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sai/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sai/Desktop/fossasia/open-event-server/src/flask-rest-jsonapi/flask_rest_jsonapi/api.py", line 133, in decorated
    return self.check_permissions(view, view_args, view_kwargs, *args, **kwargs)
  File "/home/sai/Desktop/fossasia/open-event-server/app/api/helpers/permission_manager.py", line 338, in permission_manager
    return view(*view_args, **view_kwargs)
  File "/home/sai/Desktop/fossasia/open-event-server/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/sai/.local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/sai/Desktop/fossasia/open-event-server/src/flask-rest-jsonapi/flask_rest_jsonapi/resource.py", line 68, in dispatch_request
    response = method(*args, **kwargs)
  File "/home/sai/Desktop/fossasia/open-event-server/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 56, in wrapper
    return func(*args, **kwargs)
  File "/home/sai/Desktop/fossasia/open-event-server/src/flask-rest-jsonapi/flask_rest_jsonapi/resource.py", line 254, in get
    if include.get('attributes', None).get('deleted-at', None):
AttributeError: 'NoneType' object has no attribute 'get'`

**Additional context**
Working on it

**Comment by uds5501** [comment]
@mrsaicharan1 Please try it now?

**Comment by kushthedude** [comment]
Not Reproducible

**Comment by iamareebjamal** [comment]
Fixed in https://github.com/fossasia/flask-rest-jsonapi/pull/5
