### ISSUE TITLE
Fail on fetching invoice

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-server#5858]
**Describe the bug**
I was trying to fetch the invoice with the URL but I get 500 INTERNAL SERVER ERROR 
`GET/v1/events/{event_identifier}/event-invoices{?sort,filter}`
`GET/v1/users/{user_id}/event-invoices{?sort,filter}`
Logs are attached below.

Besides, please clarify the documentation:  the title is `event invoice list of an user` but the description is `Get a single event invoice.`. Same goes for `event invoice list of an event` and `Get a single event invoice`.

**Stacktrace**
```
D/OkHttp: <-- 500 INTERNAL SERVER ERROR https://api.eventyay.com/v1/users/7622/event-invoices (228ms)
D/OkHttp: Server: nginx/1.14.0 (Ubuntu)
    Date: Sat, 04 May 2019 19:39:14 GMT
D/OkHttp: <-- 500 INTERNAL SERVER ERROR https://api.eventyay.com/v1/events/772/event-invoices (230ms)
D/OkHttp: Content-Type: application/vnd.api+json
D/OkHttp: Server: nginx/1.14.0 (Ubuntu)
D/OkHttp: Content-Length: 140
D/OkHttp: Connection: keep-alive
    Access-Control-Allow-Origin: *
    X-Sentry-ID: 0a12915859364caca8bb7aac644943af
D/OkHttp: Date: Sat, 04 May 2019 19:39:14 GMT
    Content-Type: application/vnd.api+json
    Content-Length: 140
    Connection: keep-alive
    Access-Control-Allow-Origin: *
D/OkHttp: X-Sentry-ID: 9c9a0a3d8dec47d6bac1c7737b88ba12
D/OkHttp: {"errors": [{"detail": "Unknown error", "source": {"pointer": ""}, "status": 500, "title": "Unknown error"}], "jsonapi": {"version": "1.0"}}
D/OkHttp: <-- END HTTP (140-byte body)
D/OkHttp: {"errors": [{"detail": "Unknown error", "source": {"pointer": ""}, "status": 500, "title": "Unknown error"}], "jsonapi": {"version": "1.0"}}
    <-- END HTTP (140-byte body)
    retrofit2.adapter.rxjava2.HttpException: HTTP 500 INTERNAL SERVER ERROR
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:54)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:44)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
```
**Additional context**
<img src="https://i.ibb.co/jH41sY1/Capture.png" alt="Capture" border="0">

**Comment by mrsaicharan1** [comment]
@anhanh11001 i believe that many of the android requests need this. Will fix this on priority.

**Comment by anhanh11001** [comment]
@mrsaicharan1 for the current Android app, I think this issue is not really urgent. But as we have discussed a little bit in the meeting today, if the invoice API also contains a pdf link then it would be nicer, because the mobile app cannot generate the invoice pdf by window printing like frontend.

**Comment by mrsaicharan1** [comment]
@anhanh11001 I've created an endpoint for order invoice serving. Will open an issue for docs update pertaining to the invoice generation.

**Comment by anhanh11001** [comment]
@mrsaicharan1 that's great. Thank you, so this issue can be closed now right?

**Comment by kushthedude** [comment]
@mrsaicharan1 Are we good to close it ?

**Comment by iamareebjamal** [comment]
@mrsaicharan1 Please mention the doc update here so we can close it

**Comment by mrsaicharan1** [comment]
@iamareebjamal Will do it asap

**Comment by anhanh11001** [comment]
Please update the documentation, I checked the implementation and tried to fetch order by identifier but I still get this 500 error. I'm not sure if the endpoint I'm using in here is correct but please take a look
```
D/OkHttp: <-- 500 https://api.eventyay.com/v1/orders/invoices/30e660ad-0483-40a2-8b50-021d7365cde2 (197ms)
    date: Thu, 06 Jun 2019 22:58:20 GMT
D/OkHttp: content-type: application/vnd.api+json
    content-length: 140
    set-cookie: __cfduid=d8ad96179e67bc2abb7cbdef261bed8871559861900; expires=Fri, 05-Jun-20 22:58:20 GMT; path=/; domain=.eventyay.com; HttpOnly
D/OkHttp: access-control-allow-origin: *
D/OkHttp: expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
    server: cloudflare
    cf-ray: 4e2dfd8e0fadc833-AMS
D/OkHttp: {"errors": [{"detail": "Unknown error", "source": {"pointer": ""}, "status": 500, "title": "Unknown error"}], "jsonapi": {"version": "1.0"}}
    <-- END HTTP (140-byte body)
E/InvoiceViewModel$getInvoice: Fail on fetching invoice with identifier
    retrofit2.adapter.rxjava2.HttpException: HTTP 500 
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:54)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:44)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleResumeNext$ResumeMainSingleObserver.onError(SingleResumeNext.java:80)
        at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:48)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleResumeNext.subscribeActual(SingleResumeNext.java:39)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
```

**Comment by mrsaicharan1** [comment]
@anhanh11001 I apologise for the delay. The API docs PR needs to be merged https://github.com/fossasia/open-event-server/pull/6020/
Here's the information alluding to the API request in the meantime.
<img width="1000" alt="Screenshot 2019-06-09 at 10 16 33 AM" src="https://user-images.githubusercontent.com/25197147/59160989-3fb9ff80-8aa2-11e9-8041-70f33c6bd8fa.png">

**Comment by iamareebjamal** [comment]
Implemented already
