### ISSUE TITLE
No local pdf ticket/invoice being generated for PLACED orders

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-server#5956]
**Describe the bug**

There is no local pdf being generated for *placed* orders and hence download ticket/invoice throws error on frontend.

**Expected behavior**

The file should be generated on local

**Stacktrace**

When trying to download the file : 

```
Traceback (most recent call last):
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/uddeshya/Desktop/localSetup/open-event-server/app/__init__.py", line 69, in __call__
    return self.app(environ, start_response)
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask/app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask/app.py", line 1760, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask_jwt/__init__.py", line 177, in decorator
    return fn(*args, **kwargs)
  File "/home/uddeshya/Desktop/localSetup/open-event-server/app/api/auth.py", line 327, in order_invoices
    response = make_response(send_file(file_path))
  File "/home/uddeshya/venv/lib/python3.5/site-packages/flask/helpers.py", line 595, in send_file
    file = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/uddeshya/Desktop/localSetup/open-event-server/app/../generated/invoices/orders/invoices/pdf/f4e5f26d-3e76-4fdb-96ac-9fc5a18ee90a/RU9wTitJbG/f4e5f26d-3e76-4fdb-96ac-9fc5a18ee90a.pdf'

```

**Additional details (please complete the following information):**
 - OS: [e.g. MacOS, Ubuntu, CentOS] Ubuntu
 - Python Version [e.g. `3.5`, `3.6`] 3.6

**Additional context**

Working on it

**Comment by shreyanshdwivedi** [comment]
@uds5501 this is intentional. It doesn't make sense to create invoice/ticket till it's completed.
Currently we are only creating tickets for completed/placed orders

**Comment by mrsaicharan1** [comment]
Yeah, I guess that's right. Pending orders are the orders which are in the
phase where user enter details. It can't be geenrated without details

**Comment by uds5501** [comment]
@mrsaicharan1 @shreyanshdwivedi in that case the option to download and print invoices should be removed , from the pending page, right?
