### ISSUE TITLE
No token error on Stripe

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-server#5980]
**Describe the bug**
On open-event-android, stripe payment is not successful due to fail on No such token error.

**Logs**
```
D/OkHttp: Content-Length: 193
    Connection: keep-alive
    Access-Control-Allow-Origin: *
    {"errors": [{"status": 409, "source": {"pointer": ""}, "title": "Conflict", "detail": "Request req_D3l31CujddeW7P: No such token: tok_1EfkSbBwemLKZTQekhvL1fUJ"}], "jsonapi": {"version": "1.0"}}
    <-- END HTTP (193-byte body)
D/AttendeeViewModel$chargeOrder: Failed charging the user
    retrofit2.adapter.rxjava2.HttpException: HTTP 409 CONFLICT
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:54)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:44)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
```

Context: https://github.com/fossasia/open-event-android/pull/1863

**Comment by anhanh11001** [comment]
Close as I just reread the documentation from Stripe, I used their test card but I didn't use the corresponding token but my own token
