### ISSUE TITLE
Error when trying to accept role invitation in production instance

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-server#6175]
**Describe the bug**
Error when trying to accept role invitation in production instance:

```
Error: TransitionAborted
    at s (/fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:3396:35)
    at y (/fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:5237:17)
    at S (/fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:5247:12)
    at x (/fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:5245:128)
    at E (/fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:5243:136)
    at t.invokeWithOnError (/fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:4776:242)
    at e.t.flush (/fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:4768:74)
    at e.t.flush (/fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:4781:358)
    at e.n._end (/fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:4843:9)
    at _boundAutorunEnd (/fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:4793:574)
    at a (/fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:832:61)
    at /fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:832:206
    at l (/fastboot/app/assets/vendor-37418c04d3328c260f2c1447645b3e61.js:526:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by iamareebjamal** [comment]
Please specify prod or dev

**Comment by ShridharGoel** [comment]
Updated. I thought the issue would be in both but it's there only in the production instance.

**Comment by uds5501** [comment]
@ShridharGoel @iamareebjamal tested this on frontend deployment, it seems to be working fine now. @shreyanshdwivedi can you confirm?

**Comment by uds5501** [comment]
Fixed  now
