### ISSUE TITLE
Refactoring model definitions to data classes

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-server#6465]
**Feature Description**
A ton of boilerplate code is written everywhere because of the redundant `__init__`, `__repr__` and other methods. Moving to the dataclass architecture would prove to get rid of this and focus mainly on data.

**Describe the solution you'd like**
Implementation of Data Classes

**Comment by Soniyanayak51** [comment]
Hi, I am having trouble with testing. Can you tell me the the process of running unit tests? 
`python3 -m unittest discover tests/all/` raises many module not found errors. Where can I find all the dependencies that need to be installed?

**Comment by iamareebjamal** [comment]
`nosetests tests/all`

**Comment by Soniyanayak51** [comment]
@iamareebjamal I am still getting many errors like

ERROR: Failure: InvalidRequestError (One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped class EventTopic->event_topics'. Original exception was: When initializing mapper mapped class EventTopic->event_topics, expression 'EventSubTopic' failed to locate a name ("name 'EventSubTopic' is not defined"). If this is a class name, consider adding this relationship() to the <class 'app.models.event_topic.EventTopic'> class after both dependent classes have been defined.)
.
.
.
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped class EventTopic->event_topics'. Original exception was: When initializing mapper mapped class EventTopic->event_topics, expression 'EventSubTopic' failed to locate a name ("name 'EventSubTopic' is not defined"). If this is a class name, consider adding this relationship() to the <class 'app.models.event_topic.EventTopic'> class after both dependent classes have been defined.

**Comment by iamareebjamal** [comment]
Are you running it on development branch or after some changes you made?

**Comment by Soniyanayak51** [comment]
I created a different branch. Running the command after I made changes.

**Comment by iamareebjamal** [comment]
Then there's a problem in the changes you made. Debug what's the issue

**Comment by Soniyanayak51** [comment]
@iamareebjamal but I did not make changes to the files mentioned in the error and I created the branch after updating the development branch. The last part of the error is:
`======================================================================
ERROR: Test generation of hash for a key.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/soniya51/Repos/open-event-server/tests/all/unit/api/helpers/test_storage.py", line 53, in test_generate_hash
    with patch('app.api.helpers.storage.get_settings') as get_settings:
  File "/home/soniya51/anaconda3/envs/foss_env/lib/python3.7/unittest/mock.py", line 1252, in __enter__
    self.target = self.getter()
  File "/home/soniya51/anaconda3/envs/foss_env/lib/python3.7/unittest/mock.py", line 1422, in <lambda>
    getter = lambda: _importer(target)
  File "/home/soniya51/anaconda3/envs/foss_env/lib/python3.7/unittest/mock.py", line 1105, in _importer
    thing = __import__(import_path)
  File "/home/soniya51/Repos/open-event-server/app/__init__.py", line 200, in <module>
    current_app, manager, database, jwt = create_app()
  File "/home/soniya51/Repos/open-event-server/app/__init__.py", line 87, in create_app
    BlueprintsManager.register(app)
  File "/home/soniya51/Repos/open-event-server/app/views/__init__.py", line 125, in register
    admin.add_view(AdminModelView(model, db.session))
  File "/home/soniya51/anaconda3/envs/foss_env/lib/python3.7/site-packages/flask_admin/contrib/sqla/view.py", line 329, in __init__
    menu_icon_value=menu_icon_value)
  File "/home/soniya51/anaconda3/envs/foss_env/lib/python3.7/site-packages/flask_admin/model/base.py", line 818, in __init__
    self._refresh_cache()
  File "/home/soniya51/anaconda3/envs/foss_env/lib/python3.7/site-packages/flask_admin/model/base.py", line 895, in _refresh_cache
    self._list_columns = self.get_list_columns()
  File "/home/soniya51/anaconda3/envs/foss_env/lib/python3.7/site-packages/flask_admin/model/base.py", line 1035, in get_list_columns
    only_columns=self.column_list or self.scaffold_list_columns(),
  File "/home/soniya51/anaconda3/envs/foss_env/lib/python3.7/site-packages/flask_admin/contrib/sqla/view.py", line 415, in scaffold_list_columns
    for p in self._get_model_iterator():
  File "/home/soniya51/anaconda3/envs/foss_env/lib/python3.7/site-packages/flask_admin/contrib/sqla/view.py", line 351, in _get_model_iterator
    return model._sa_class_manager.mapper.iterate_properties
  File "/home/soniya51/anaconda3/envs/foss_env/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 2059, in iterate_properties
    configure_mappers()
  File "/home/soniya51/anaconda3/envs/foss_env/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3225, in configure_mappers
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped class EventTopic->event_topics'. Original exception was: When initializing mapper mapped class EventTopic->event_topics, expression 'EventSubTopic' failed to locate a name ("name 'EventSubTopic' is not defined"). If this is a class name, consider adding this relationship() to the <class 'app.models.event_topic.EventTopic'> class after both dependent classes have been defined.
-------------------- >> begin captured logging << --------------------
/home/soniya51/anaconda3/envs/foss_env/lib/python3.7/site-packages/envparse.py: DEBUG: envfile not found at /home/soniya51/Repos/open-event-server/app/.env, looking in parent dir.
/home/soniya51/anaconda3/envs/foss_env/lib/python3.7/site-packages/envparse.py: DEBUG: envfile not found at /home/soniya51/Repos/open-event-server/.env, looking in parent dir.
/home/soniya51/anaconda3/envs/foss_env/lib/python3.7/site-packages/envparse.py: DEBUG: envfile not found at /home/soniya51/Repos/.env, looking in parent dir.
/home/soniya51/anaconda3/envs/foss_env/lib/python3.7/site-packages/envparse.py: DEBUG: envfile not found at /home/soniya51/.env, looking in parent dir.
/home/soniya51/anaconda3/envs/foss_env/lib/python3.7/site-packages/envparse.py: DEBUG: envfile not found at /home/.env, looking in parent dir.
/home/soniya51/anaconda3/envs/foss_env/lib/python3.7/site-packages/envparse.py: DEBUG: envfile not found at /.env, looking in parent dir.
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 46 tests in 0.817s

FAILED (errors=28)
`

**Comment by iamareebjamal** [comment]
In which files did you make the changes. A very standard way to test if the errors are caused by you or already there is simply reverting your changes and running the tests. If you are still getting errors on unmodified development branch, we can take a look at what's wrong. However, chances are that the errors are due to your changes or maybe setting database url or app config wrong, because all the tests are passing in CI. 

Tests failure in files you did not touch is expected in any project with more than 3 files. Anything can be imported across packages breaking multiple things

**Comment by Soniyanayak51** [comment]
Hi @iamareebjamal, extremely sorry to bother again. I have added data classes for event related modules. But I still have a problem in testing. I am getting a persistent error 
`AttributeError: 'NoneType' object has no attribute 'drivername'`
The error is in flask_sqlalchemy package and I thing I am setting the DATABASE_URL wrong.
Error Log example:
```
ERROR: test_generate_hash (unit.api.helpers.test_storage.TestStorageHelperValidation)
Test generation of hash for a key.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/soniya51/Repos/open-event-server/tests/all/unit/api/helpers/test_storage.py", line 53, in test_generate_hash
    with patch('app.api.helpers.storage.get_settings') as get_settings:
  File "/home/soniya51/anaconda3/envs/foss_env/lib/python3.7/unittest/mock.py", line 1252, in __enter__
    self.target = self.getter()
  File "/home/soniya51/anaconda3/envs/foss_env/lib/python3.7/unittest/mock.py", line 1422, in <lambda>
    getter = lambda: _importer(target)
  File "/home/soniya51/anaconda3/envs/foss_env/lib/python3.7/unittest/mock.py", line 1105, in _importer
    thing = __import__(import_path)
  File "/home/soniya51/Repos/open-event-server/app/__init__.py", line 202, in <module>
    current_app, manager, database, jwt = create_app()
  File "/home/soniya51/Repos/open-event-server/app/__init__.py", line 171, in create_app
    add_engine_pidguard(db.engine)
  File "/home/soniya51/.local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 937, in engine
    return self.get_engine()
  File "/home/soniya51/.local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 956, in get_engine
    return connector.get_engine()
  File "/home/soniya51/.local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 560, in get_engine
    options = self.get_options(sa_url, echo)
  File "/home/soniya51/.local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 575, in get_options
    self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/soniya51/.local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 877, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'

```

**Comment by Soniyanayak51** [comment]
I am raising a WIP PR. Could you please review it?

**Comment by iamareebjamal** [comment]
`TEST_DATABASE_URL=sqlite:// APP_CONFIG=config.TestingConfig nosetests tests/all`
