### ISSUE TITLE
Question: Error on starting server

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-server#6711]
**Describe the bug**

After updating the fork, Server is not able to start due to name collision. I am not sure if it is issue on my local.

**Stacktrace**

```py
Traceback (most recent call last):
  File "create_db.py", line 7, in <module>
    from app.instance import current_app
  File "/Users/kush/open-event-server/app/instance.py", line 213, in <module>
    current_app = create_app()
  File "/Users/kush/open-event-server/app/instance.py", line 200, in create_app
    from app.views.elastic_cron_helpers import cron_rebuild_events_elasticsearch
  File "/Users/kush/open-event-server/app/views/elastic_cron_helpers.py", line 10, in <module>
    from app.api.helpers.tasks import celery
  File "/Users/kush/open-event-server/app/api/helpers/tasks.py", line 59, in <module>
    celery = make_celery()
  File "/Users/kush/open-event-server/app/api/helpers/tasks.py", line 55, in make_celery
    app = app or create_app()
  File "/Users/kush/open-event-server/app/instance.py", line 85, in create_app
    BlueprintsManager.register(app)
  File "/Users/kush/open-event-server/app/views/blueprints.py", line 109, in register
    base_template='admin_base.html')
  File "/Users/kush/open-event-server/venv/lib/python3.7/site-packages/flask_admin/base.py", line 522, in __init__
    self._set_admin_index_view(index_view=index_view, endpoint=endpoint, url=url)
  File "/Users/kush/open-event-server/venv/lib/python3.7/site-packages/flask_admin/base.py", line 567, in _set_admin_index_view
    self.add_view(self.index_view)
  File "/Users/kush/open-event-server/venv/lib/python3.7/site-packages/flask_admin/base.py", line 540, in add_view
    self.app.register_blueprint(view.create_blueprint(self))
  File "/Users/kush/open-event-server/venv/lib/python3.7/site-packages/flask/app.py", line 98, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/kush/open-event-server/venv/lib/python3.7/site-packages/flask/app.py", line 1160, in register_blueprint
    % (blueprint, self.blueprints[blueprint.name], blueprint.name)
AssertionError: A name collision occurred between blueprints <flask.blueprints.Blueprint object at 0x114050eb8> and <flask.blueprints.Blueprint object at 0x113072d30>. Both share the same name "admin". Blueprints that are created on the fly need unique names.
```

**Comment by kushthedude** [comment]
cc : @iamareebjamal

**Comment by iamareebjamal** [comment]
`find . -name \*.pyc -delete
`

**Comment by kushthedude** [comment]
No good

**Comment by iamareebjamal** [comment]
Working fine for me, suneet and dredd

**Comment by iamareebjamal** [comment]
Try ELASTICSEARCH_ENABLED=false if it is not already

**Comment by kushthedude** [comment]
> Try ELASTICSEARCH_ENABLED=false if it is not already

This was the issue
