### ISSUE TITLE
Create tests for all created_at

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6722]
Create tests verifying that all created_at in all models are set to current time

**Comment by diru1100** [comment]
can I take up this issue?

**Comment by iamareebjamal** [comment]
Yes

**Comment by diru1100** [comment]
I have created a DB called opevtest before writing test code for this.
**1)** Do I have to run the server in localhost to see my test code ?
**2)****I am getting the following error as some module is not found while running test code :**


(venv) Rohits-MacBook-Pro:open-event-server rohitdandamudi$ python3 -m unittest tests/all/unit/api/helpers/test_created_at.py 
E
======================================================================
ERROR: test_createdat_session (tests.all.unit.api.helpers.test_created_at.TestCreatedatValidation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rohitdandamudi/Desktop/FOSSASIA/open-event-server/venv/lib/python3.7/site-packages/sqlalchemy/ext/declarative/clsregistry.py", line 294, in __call__
    x = eval(self.arg, globals(), self._dict)
  File "<string>", line 1, in <module>
NameError: name 'Speaker' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rohitdandamudi/Desktop/FOSSASIA/open-event-server/tests/all/unit/api/helpers/test_created_at.py", line 26, in test_createdat_session
    s=Session()
  File "<string>", line 2, in __init__
  File "/Users/rohitdandamudi/Desktop/FOSSASIA/open-event-server/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 376, in _new_state_if_none
    state = self._state_constructor(instance, self)
  File "/Users/rohitdandamudi/Desktop/FOSSASIA/open-event-server/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/rohitdandamudi/Desktop/FOSSASIA/open-event-server/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 202, in _state_constructor
    self.dispatch.first_init(self, self.class_)
  File "/Users/rohitdandamudi/Desktop/FOSSASIA/open-event-server/venv/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/Users/rohitdandamudi/Desktop/FOSSASIA/open-event-server/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3360, in _event_on_first_init
    configure_mappers()
  File "/Users/rohitdandamudi/Desktop/FOSSASIA/open-event-server/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3248, in configure_mappers
    mapper._post_configure_properties()
  File "/Users/rohitdandamudi/Desktop/FOSSASIA/open-event-server/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 1947, in _post_configure_properties
    prop.init()
  File "/Users/rohitdandamudi/Desktop/FOSSASIA/open-event-server/venv/lib/python3.7/site-packages/sqlalchemy/orm/interfaces.py", line 196, in init
    self.do_init()
  File "/Users/rohitdandamudi/Desktop/FOSSASIA/open-event-server/venv/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1913, in do_init
    self._process_dependent_arguments()
  File "/Users/rohitdandamudi/Desktop/FOSSASIA/open-event-server/venv/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1975, in _process_dependent_arguments
    self.target = self.entity.persist_selectable
  File "/Users/rohitdandamudi/Desktop/FOSSASIA/open-event-server/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/rohitdandamudi/Desktop/FOSSASIA/open-event-server/venv/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1880, in entity
    argument = self.argument()
  File "/Users/rohitdandamudi/Desktop/FOSSASIA/open-event-server/venv/lib/python3.7/site-packages/sqlalchemy/ext/declarative/clsregistry.py", line 306, in __call__
    % (self.prop.parent, self.arg, n.args[0], self.cls)
sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class Session->sessions, expression 'Speaker' failed to locate a name ("name 'Speaker' is not defined"). If this is a class name, consider adding this relationship() to the <class 'app.models.session.Session'> class after both dependent classes have been defined.

----------------------------------------------------------------------
Ran 1 test in 0.043s

FAILED (errors=1)

**3)** I have imported all instances of created_at in all models and checking it with datetime.now()

**Comment by iamareebjamal** [comment]
The models have to be manually imported for them to be registered. Either run all tests using `nosetests tests/` or add temporary import of `from app.api import routes` in the test file

**Comment by codedsun** [comment]
Taking this up @diru1100  as it has been 8 days and their is no work from your side. Thanks

**Comment by diru1100** [comment]
I was out of station and was unable to work on this. Can I please work on this till Sunday if possible?

**Comment by mrsaicharan1** [comment]
@codedsun You seem to have 5-6 open PRs already. Please try wrapping up those before moving on to new ones.

**Comment by codedsun** [comment]
@diru1100 Ok sure
