### ISSUE TITLE
Resize image task not working

### ISSUE THREAD

**Issue by codedsun** [fossasia/open-event-server#6725]
**Describe the bug**
Requests throwing invalid image for evry different image I upload

Error

```
[2020-01-05 23:55:47,736: INFO/ForkPoolWorker-1] User image resizing tasks started http://127.0.0.1:5000/static/media/temp/images/4f000fa1-7704-4577-bf67-4ba7a5305e92/QnZUejhBbW/bb21d8fc-dcc1-4f3c-959b-05cc23ce76aa.jpeg
[2020-01-05 23:55:47,750: DEBUG/ForkPoolWorker-1] Starting new HTTP connection (1): 127.0.0.1:5000
[2020-01-05 23:55:47,836: DEBUG/ForkPoolWorker-1] http://127.0.0.1:5000 "GET /static/media/temp/images/4f000fa1-7704-4577-bf67-4ba7a5305e92/QnZUejhBbW/bb21d8fc-dcc1-4f3c-959b-05cc23ce76aa.jpeg HTTP/1.1" 500 None
[2020-01-05 23:55:47,846: ERROR/ForkPoolWorker-1] Task resize.user.images[ea3c0cbe-88a3-4811-9f93-feb6de8579bc] raised unexpected: OSError('Corrupt/Invalid Image')
Traceback (most recent call last):
  File "/Users/codedsun/Documents/FOSS/open-event-server/app/api/helpers/files.py", line 84, in create_save_resized_image
    im = Image.open(image_file)
  File "/usr/local/lib/python3.7/site-packages/PIL/Image.py", line 2818, in open
    raise IOError("cannot identify image file %r" % (filename if filename else fp))
OSError: cannot identify image file <_io.BytesIO object at 0x108ceba10>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_celeryext/app.py", line 101, in __call__
    res = Task.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/celery.py", line 158, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/_compat.py", line 57, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/celery.py", line 153, in _inner
    return f(*args, **kwargs)
  File "/Users/codedsun/Documents/FOSS/open-event-server/app/api/helpers/tasks.py", line 153, in resize_user_images_task
    uploaded_images = create_save_image_sizes(original_image_url, 'speaker-image', user.id)
  File "/Users/codedsun/Documents/FOSS/open-event-server/app/api/helpers/files.py", line 160, in create_save_image_sizes
    'original_image_url': create_save_resized_image(image_file, 0, 0, 0, original_upload_path, resize=False),
  File "/Users/codedsun/Documents/FOSS/open-event-server/app/api/helpers/files.py", line 86, in create_save_resized_image
    raise IOError("Corrupt/Invalid Image")
OSError: Corrupt/Invalid Image

```

**Expected behavior**
This should not happen

**Comment by iamareebjamal** [comment]
See the URL it is trying to fetch and its response. This is a local issue
