### ISSUE TITLE
Failing event fee notification task

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-server#6820]
**Describe the bug**
```
[2020-02-06 06:42:45,701: ERROR/ForkPoolWorker-3] Task send.event.fee.notification[8ec9e2f2-5cd3-4cf0-b42f-ea2a941d3a0d] raised unexpected: KeyError('title')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_celeryext/app.py", line 96, in __call__
    res = Task.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/celery.py", line 161, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/_compat.py", line 57, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/celery.py", line 156, in _inner
    return f(*args, **kwargs)
  File "/Users/saicharan/Desktop/open-event-server/app/api/helpers/scheduled_jobs.py", line 158, in send_event_fee_notification
    new_invoice.event_id,
  File "/Users/saicharan/Desktop/open-event-server/app/api/helpers/notification.py", line 165, in send_notif_monthly_fee_payment
    title = notification['title'].format(date=previous_month, event_name=event_name)
KeyError: 'title'
```
Due to the aforementioned error, the event fee notification task fails every month.

**Comment by mrsaicharan1** [comment]
@iamareebjamal I see that this has occurred before. I think we need a test for this as well.

**Comment by mrsaicharan1** [comment]
This should've been tested properly - https://github.com/fossasia/open-event-server/issues/6769

**Comment by iamareebjamal** [comment]
Fixed in reimplementation
