### ISSUE TITLE
Admin can not change the details of any user

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-server#6829]
Admin can not change details of other users, as admin should be able to do so.

Stacktrace :
```py
Traceback (most recent call last):
  File "/Users/kush/open-event-server/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/Users/kush/open-event-server/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type integer: "a1d66f95"
LINE 3: WHERE events.id = 'a1d66f95'
                          ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kush/open-event-server/venv/lib/python3.7/site-packages/sentry_sdk/integrations/flask.py", line 70, in sentry_patched_wsgi_app
    response = self.handle_exception(e)
  File "/Users/kush/open-event-server/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/kush/open-event-server/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/kush/open-event-server/venv/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/kush/open-event-server/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/kush/open-event-server/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/Users/kush/open-event-server/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/kush/open-event-server/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/Users/kush/open-event-server/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/kush/open-event-server/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/Users/kush/open-event-server/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/Users/kush/open-event-server/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type integer: "a1d66f95"
LINE 3: WHERE events.id = 'a1d66f95'
                          ^

[SQL: SELECT events.deleted_at AS events_deleted_at, events.id AS events_id, events.identifier AS events_identifier, events.name AS events_name, events.external_event_url AS events_external_event_url, events.logo_url AS events_logo_url, events.starts_at AS events_starts_at, events.ends_at AS events_ends_at, events.timezone AS events_timezone, events.is_event_online AS events_is_event_online, events.latitude AS events_latitude, events.longitude AS events_longitude, events.location_name AS events_location_name, events.searchable_location_name AS events_searchable_location_name, events.is_featured AS events_is_featured, events.is_promoted AS events_is_promoted, events.description AS events_description, events.original_image_url AS events_original_image_url, events.thumbnail_image_url AS events_thumbnail_image_url, events.large_image_url AS events_large_image_url, events.show_remaining_tickets AS events_show_remaining_tickets, events.icon_image_url AS events_icon_image_url, events.owner_name AS events_owner_name, events.is_map_shown AS events_is_map_shown, events.has_owner_info AS events_has_owner_info, events.owner_description AS events_owner_description, events.is_sessions_speakers_enabled AS events_is_sessions_speakers_enabled, events.privacy AS events_privacy, events.state AS events_state, events.event_type_id AS events_event_type_id, events.event_topic_id AS events_event_topic_id, events.event_sub_topic_id AS events_event_sub_topic_id, events.ticket_url AS events_ticket_url, events.code_of_conduct AS events_code_of_conduct, events.schedule_published_on AS events_schedule_published_on, events.is_ticketing_enabled AS events_is_ticketing_enabled, events.is_donation_enabled AS events_is_donation_enabled, events.is_ticket_form_enabled AS events_is_ticket_form_enabled, events.payment_country AS events_payment_country, events.payment_currency AS events_payment_currency, events.paypal_email AS events_paypal_email, events.is_tax_enabled AS events_is_tax_enabled, events.is_billing_info_mandatory AS events_is_billing_info_mandatory, events.can_pay_by_paypal AS events_can_pay_by_paypal, events.can_pay_by_stripe AS events_can_pay_by_stripe, events.can_pay_by_cheque AS events_can_pay_by_cheque, events.can_pay_by_bank AS events_can_pay_by_bank, events.can_pay_onsite AS events_can_pay_onsite, events.can_pay_by_omise AS events_can_pay_by_omise, events.can_pay_by_alipay AS events_can_pay_by_alipay, events.can_pay_by_paytm AS events_can_pay_by_paytm, events.cheque_details AS events_cheque_details, events.bank_details AS events_bank_details, events.onsite_details AS events_onsite_details, events.created_at AS events_created_at, events.pentabarf_url AS events_pentabarf_url, events.ical_url AS events_ical_url, events.xcal_url AS events_xcal_url, events.is_sponsors_enabled AS events_is_sponsors_enabled, events.refund_policy AS events_refund_policy, events.is_stripe_linked AS events_is_stripe_linked, events.discount_code_id AS events_discount_code_id
FROM events
WHERE events.id = %(id_1)s]
[parameters: {'id_1': 'a1d66f95'}]
(Background on this error at: http://sqlalche.me/e/9h9h)
```

**Comment by mrsaicharan1** [comment]
I'll take this up.

**Comment by codedsun** [comment]
@iamareebjamal - 
The request body has the wrong event-id in relationship. Also, should the relationships be sent from client-side while patching the user?
```
{"data":{"id":"2","attributes":{"email":"ss@gmail.com","is-admin":false,"is-user-owner":true,"is-user-organizer":false,"is-user-coorganizer":false,"is-user-track-organizer":false,"is-user-moderator":false,"is-user-registrar":false,"is-sales-admin":false,"is-marketer":false,"was-registered-with-order":false,"first-name":"ss","last-name":"Singh","details":"Hi","contact":null,"avatar-url":null,"icon-image-url":null,"small-image-url":null,"thumbnail-image-url":null,"original-image-url":null,"facebook-url":null,"instagram-url":null,"twitter-url":null,"google-plus-url":null,"deleted-at":null,"billing-contact-name":null,"billing-phone":null,"billing-country":null,"company":null,"billing-address":null,"billing-city":null,"billing-zip-code":null,"billing-tax-info":null,"billing-additional-info":null,"billing-state":null},"relationships":{"owner-events":{"data":[{"type":"event","id":"2050ab87"}]},"organizer-events":{"data":[]},"coorganizer-events":{"data":[]},"track-organizer-events":{"data":[]},"registrar-events":{"data":[]},"moderator-events":{"data":[]},"marketer-events":{"data":[{"type":"event","id":"95a16dad"},{"type":"event","id":"1d4b396e"},{"type":"event","id":"2050ab87"}]},"sales-admin-events":{"data":[{"type":"event","id":"95a16dad"},{"type":"event","id":"1d4b396e"},{"type":"event","id":"2050ab87"}]}},"type":"user"}}'

```

The relationships is

**Comment by iamareebjamal** [comment]
No, they shouldn't. But it's the amazing ember-data which decides what it should do for us

**Comment by codedsun** [comment]
Then I should fix for the relationships that are being sent wrong at the first place from the server. Correct?

**Comment by iamareebjamal** [comment]
Fix should be in frontend. It shouldn't send those relationships. Set them to readonly

**Comment by mariobehling** [comment]
We will follow up on this during the development of open event next.
