### ISSUE TITLE
Celery not working

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-server#6832]
Celery is not starting as `ENABLE_ELASTICSEARCH` argument has been removed from `.env`.
`ENABLE_ELASTICSEARCH = False` to make celery worker start or else it throws error :
```py
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kush/open-event-server/venv/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/kush/open-event-server/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/kush/open-event-server/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /static/media/temp/images/3fb7ac00-7323-4e34-b427-6d71e9f5121c/SjNCNjk3K1/86c7109d-2332-4507-90eb-138dec5e8bb9.jpeg (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x111190410>: Failed to establish a new connection: [Errno 61] Connection refused'))
```

**Comment by kushthedude** [comment]
@iamareebjamal I think elastic search initialisation is still not removed. Should this be `ENABLE_ELASTICSEARCH = False` explicitly mentioned in the env as before?

**Comment by iamareebjamal** [comment]
No, the logic should be removed from celery config

**Comment by iamareebjamal** [comment]
Working correctly
